### ISSUE TITLE
有關「中文習慣」

### ISSUE THREAD

**Issue by aikahiiragi** [lxgw/LxgwWenKai#1]
非常欣賞大大的「霞鶩晰黑」，製作中文傳承字形的字體。我一向喜歡選用傳承字形的字體，這符合了我的中文使用習慣。可是看到這項目，當中卻把字形修改成較接近GB寫法的部分，稱作「修改部分字形使其更加接近『中文使用習慣』」，個人十分反感。我不會反對有傾向GB寫法習慣或「新字形」習慣的字體，但拜託不要把它們稱作「中文使用習慣」，說得好像是傳承中文字形並不是中文使用習慣似的。非常希望大大可以修正這裏的說明，說清楚是「GB寫法習慣」或「新字形習慣」。強烈拜謝！

**Comment by Hulenkius** [comment]
私以爲此處的「中文使用習慣」是相對於「日文使用習慣」而言的……而且個人也希望能製作不同標準的字形。

**Comment by aikahiiragi** [comment]
可是圖例裏所示的是中文使用習慣，至少翻開中文印刷書刊，黑色的「置」比藍色的「置」常見。「羽」偏旁也一樣。這些並不是「日文」使用習慣，而確實是中文使用習慣。

**Comment by lxgw** [comment]
抱歉，是我措辭不當，沒有考慮到傳承字形的情況，才會把新字形籠統地稱爲「中文習慣」。GitHub 頁面已修改，感謝您的反饋。

**Comment by aikahiiragi** [comment]
太好了！感謝明白和修改，真的謝謝！
要是思源那邊能學習大大的知識和態度，而不是堅持錯誤，現在應該就好得多了T_T
