### ISSUE TITLE
“垂”部问题

### ISSUE THREAD

**Issue by CaiMiao** [lxgw/LxgwWenKai#10]
最下两横可否修改成上长下短？

**Comment by CL-Jeremy** [comment]
似乎只有中国大陆是上长下短……这个字在各地都是常用字，大概不便修改

![Bildschirmfoto 2021-02-22 um 07 40 03](https://user-images.githubusercontent.com/1714243/108673415-e8f99100-74e3-11eb-825b-1619bf6bb78c.png)

**Comment by CL-Jeremy** [comment]
上图的冬青繁体即是在符合台标的前提下，不似思源模仿「重」字结构而直接沿用原版字形制作的，个人认为这个标准接受度可能是比较高的（香港柯老师的俪黑 Pro 也是这个字形）

**Comment by lxgw** [comment]
这个貌似构不成字形上的问题，两种写法都不算错。
