### ISSUE TITLE
关于符号没对齐问题

### ISSUE THREAD

**Issue by cjlhll** [lxgw/LxgwWenKai#100]
你好，我在两个代码编辑工具里，尖角号都和文字没有对齐居中呢？
应该是按照最高字体居中了。应该没啥问题。就是有点别扭。不知道有没有什么好的方案优化一下。
![QQ截图20230112165734](https://user-images.githubusercontent.com/26736892/212022961-b911f226-fe08-437b-83a9-37c02b95500c.png)
![QQ截图20230112165712](https://user-images.githubusercontent.com/26736892/212022976-9861070c-ccf8-41d9-ba9f-d4e4940a2a76.png)

**Comment by lxgw** [comment]
应该是处理成数字的大于小于，与数字的中部对齐了。

**Comment by cjlhll** [comment]
> 

可以优化吗。

**Comment by lxgw** [comment]
建议更换其他字体。
