### ISSUE TITLE
等宽字体不能被 Mac 识别为固定宽度字体，有些软件无法设置该字体，如：SecureCRT

### ISSUE THREAD

**Issue by shenghui0779** [lxgw/LxgwWenKai#101]
- 安装了 <霞鹜文楷等宽> 字体
<img width="935" alt="image" src="https://user-images.githubusercontent.com/67535398/212277740-662868fd-f129-4f44-9c36-68ce4f13fcdf.png">

- 没有出现在 <固定宽度> 中
<img width="935" alt="image" src="https://user-images.githubusercontent.com/67535398/212277610-800b5153-c147-4279-ab50-abe123c8df18.png">

**Comment by lxgw** [comment]
建议更换其他字体，后续更新中可能会取消等宽版，以减轻更新时的负担。

**Comment by lxgw** [comment]
由于本人没有 Mac 设备，所以本问题恕无法复现，请您谅解。

（Windows 上会被识别为等宽字体，可在命令提示符显示）

另外，后续更新中可能会撤销等宽版，以减轻更新时的负担。

**Comment by shenghui0779** [comment]
撤销等宽版也太可惜了

**Comment by shenghui0779** [comment]
我看这个Issue：https://github.com/lxgw/LxgwWenKai/issues/31 中有提到设置等宽属性，我想试一下，但是里面的链接已经失效了

**Comment by shenghui0779** [comment]
@lxgw 等宽字体真的很好，我已经安利很多程序员同事了，别放弃它啊！

**Comment by ab9986** [comment]
中文 ”“与汉字不是等宽的

**Comment by NightFurySL2001** [comment]
@shenghui0779 @dalugm 能测试看这版有问题吗？
[LXGWWenKaiMono-Regular.zip](https://github.com/user-attachments/files/17179629/LXGWWenKaiMono-Regular.zip)

**Comment by flczcy** [comment]
我的注释, 某些字符串, markdown 文档表格 等全用的是这个等宽版的, 撤销实在太可惜了

**Comment by dalugm** [comment]
> 能测试看这版有问题吗？

@NightFurySL2001 抱歉，我的邮箱一直没有收到通知（windows 桌面版邮件真是拉胯），直到今天偶尔打开了网页版邮箱才看到通知邮件

我现在已经不用 mac 了，恐怕帮不上你
