### ISSUE TITLE
为全角标点添加 halt feature（可变为半角标点）

### ISSUE THREAD

**Issue by ouuan** [lxgw/LxgwWenKai#104]
希望能为全角标点添加 [halt](https://learn.microsoft.com/zh-cn/typography/opentype/spec/features_fj#tag-halt) feature。

一个使用场景是在 CSS 中使用 [`font-feature-setings`](https://developer.mozilla.org/en-US/docs/Web/CSS/font-feature-settings) 来将全角标点变为半角显示，从而可以实现[标点挤压](https://www.w3.org/TR/clreq/#punctuation_width_adjustment)。（网页标点挤压也有其他实现方式，但通过 font feature 来实现遇到的问题会相对较少，其他解决方式更像是 workaround。）

思源宋体支持 halt 和 [palt](https://learn.microsoft.com/zh-cn/typography/opentype/spec/features_pt#palt) 两个 feature，对于常见的全角标点效果貌似是一样的，所以也可以考虑同时添加 palt feature。

我自己简单尝试了一下为几个标点添加 halt feature，即在 ufo 的 `features.fea` 中添加下面的内容：

```
feature halt {
  position \uFF0C <0 0 -500 0>;
  position \u3002 <0 0 -500 0>;
  position \uFF08 <-500 0 -500 0>;
  position \uFF09 <0 0 -500 0>;
} halt;
```

效果如图所示：

![demo](https://user-images.githubusercontent.com/30581822/216630679-02432a80-2e9f-426d-b8f1-1b71da00b54d.png)

**Comment by lxgw** [comment]
由于涉及 20 个以上的字体文件，故尚无修改  OpenType 特性的计划。

**Comment by yisibl** [comment]
随着 Chrome 123 正式发布了CJK 字体的「标点挤压功能」，越来越多的用户可以享受到这一改进。但目前 Chrome 中的该功能依赖字体具有 `halt` 或 `chws` 特性，所以强烈建议重新考虑该功能。

https://twitter.com/yisibl/status/1764871494293979147

**Comment by lxgw** [comment]
重新打开这个 issue，下个版本将会加入 `halt` 和 `vhal` 特性，用于 Chrome 标点挤压。

下图为「霞鹜文楷 TC」的测试效果，如无意外，其他字形版本也会跟进。
![50a056714e50ab2a5c2e6551b3cec782](https://github.com/user-attachments/assets/9f9abd19-7999-4d03-91b2-3124e11dacfb)
