### ISSUE TITLE
请问，升级新版本字体的方式是直接覆盖安装吗？

### ISSUE THREAD

**Issue by Jimmy20220531** [lxgw/LxgwWenKai#105]
【旧版字体卸载删除】后再【安装新版字体】？还是【直接覆盖安装新版本字体】呢？
望大佬解惑。

**Comment by lxgw** [comment]
先覆盖试试，如果还是旧版就先重启或着注销再登录，更彻底的办法就是删除旧版再安装新版。

Windows XP 及以往版本的 Windows 不支持覆盖安装，只能删除旧版再安装新版。
