### ISSUE TITLE
打开阅读软件时没有问题，但点进看小说软件会闪退，只有这个字体会这样lxgw的A丸不会闪退而且模块版本更老

### ISSUE THREAD

**Issue by Linco-me** [lxgw/LxgwWenKai#106]
阅读
io.legado.app.release
https://www.coolapk.com/apk/io.legado.app.release

**Comment by lxgw** [comment]
请您选用其他字体,给您带来不便深表歉意.

**Comment by lxgw** [comment]
1. 有关手机字体模块的问题请不要在本字体项目的 issue 内反馈。
2. 请您选用其他字体或其他人制作的字体模块，给您带来不便深表歉意。
3. 本人态度可能不好，请见谅。

**Comment by onichan0923** [comment]
建议向软件开发者而非字体作者反应此问题。
字体作者没有义务解决此类问题。
