### ISSUE TITLE
能否支持中英文等宽？

### ISSUE THREAD

**Issue by WingDust** [lxgw/LxgwWenKai#107]
能否支持中英文等宽？ 中文是英文两倍宽，像 Iosevka 字体的 等宽

**Comment by lxgw** [comment]
Releases 里已经提供等宽版了，名称带 Mono 的就是。是等宽版用起来有问题吗？

**Comment by WingDust** [comment]
我在写代码时做字符对齐时，需要中英文等宽

**Comment by lxgw** [comment]
请您进入 [Release](https://github.com/lxgw/LxgwWenKai/releases/latest) 界面下载最新字体，下图画框为等宽字体。

![image](https://user-images.githubusercontent.com/51902309/233667530-bd8f7fc9-f2d7-4ef8-b68f-1ef9317951c4.png)
