### ISSUE TITLE
Korean(Hangul) '즉' looks like '즘'

### ISSUE THREAD

**Issue by d2n0s4ur** [lxgw/LxgwWenKai#108]
U+C989(즉) looks like U+C998(즘)

U+C989 must looks like this:
![image](https://user-images.githubusercontent.com/43975014/234612136-36529b51-857d-48ce-94fa-7249121e30e3.png)

but now, U+C989 looks like:
![image](https://user-images.githubusercontent.com/43975014/234612363-dbdb71f7-91d3-49de-8652-3b1b8a078e49.png)

**Comment by lxgw** [comment]
It will be fixed in the next version.
