### ISSUE TITLE
等宽箭头符号

### ISSUE THREAD

**Issue by guoyunhe** [lxgw/LxgwWenKai#109]
我用的是落霞孤骛等宽，在展示一些上下左右箭头符号时，我发现箭头是全角宽度。而像 Source Code Pro 等等宽字体中，箭头符号通常也是半角宽度。很多终端程序和编辑器也是按照箭头是半角设计的，比如我在 Linux 终端（Konsole）里打`a→b`：

![image](https://github.com/lxgw/LxgwWenKai/assets/5836790/20231894-2cf9-4817-bcac-10e069800c10)

发现箭头和后面的字母是挤在一起的。

对比 Source Code Pro 的效果：

![image](https://github.com/lxgw/LxgwWenKai/assets/5836790/1967c3ab-8a37-4b26-aa5c-a4bca106ad29)

可以看到等宽箭头为半角时宽度，能获得更好的效果。

**Comment by lu-jialin** [comment]
通过对比和测试有一些更完整的信息。

其它等宽字体应该是专门优化修改了箭头、盒子之类的常用unicode。但在CJK字体之前的其它字符有些其实还是和终端显示冲突的。例如```Source Code Pro```下的```0x26e7```：
![](https://github.com/lxgw/LxgwWenKai/assets/80277591/01c00847-9411-41dd-acc6-5afbdebb8a67)

应该是终端显示的文字排列算法中，对于CJK的区域起始点```0x2e08```之前的字符都按半角宽度算，但字体里面绘制了```[0x2000, 0x2e7f]```之间的一些字符，然后设置为全角。所以整体调整这个区间的字符设置等宽再平移能有一些效果。

除此之外```[0x0000, 0x1fff]```区间内还多绘制了两个字符，可能是因为日语中比较常用，分别是```฿``` ```࿖```：
![wenkai-0x0e3f](https://github.com/lxgw/LxgwWenKai/assets/80277591/b0ca81e4-c9b3-4863-89ea-56ebaa30e729)
![wenkai-0x0fd6](https://github.com/lxgw/LxgwWenKai/assets/80277591/e5d94e48-df6d-4521-a7f1-6d8f0646acfd)


另外在```[0x2000,0x2e7f]```区间中有一些字符应该是在日语中有特殊的用法，所以被单独设置成了半角，就是说它们原本就是等宽的：
- ```[0x2373, 0x237a]```
- ```[0x2070, 0x2089]```
- ```0x2052```
- ```0x203e```
- ```[0x2039, 0x203a]```
- ```[0x2032, 0x2037]```
- ```[0x2012, 0x2013]```
- ```0x2011```

这些字符调整之后反而会错位。这是为自己大概看几遍筛查的，可能会有错漏，不知道日语里有没有什么相应的的标准文件说明。

批量调整之后还是有一些小问题，那就得微调了：
![wenkai-new-after](https://github.com/lxgw/LxgwWenKai/assets/80277591/325ea323-b7fa-49fb-99cc-d4a10edbce31)
![wenkai-vss](https://github.com/lxgw/LxgwWenKai/assets/80277591/7cbefdca-faa2-4c0b-87e8-f141e463ad20)

顺便一提感觉霞鹜文楷在等宽环境里的伪加粗、伪斜体效果都很不错

**Comment by rLry** [comment]
同，省略号亦有挤压
