### ISSUE TITLE
屏幕版在一些网页非文字元素显示不正常

### ISSUE THREAD

**Issue by ziliudi** [lxgw/LxgwWenKai#111]
![FireShot Capture 291 - 博文：修改 - draft blogger com](https://github.com/lxgw/LxgwWenKai/assets/58017099/e6bed3e2-98a8-48f7-92b8-a98e09db3eb1)

比如谷歌blogger的编辑栏，比如微博的转评两个按钮。

**Comment by lxgw** [comment]
如果您用的是 Firefox 的话，建议不要使用强制应用字体功能。

**Comment by ziliudi** [comment]
> 如果您用的是 Firefox 的话，更换其他字体也是一样的效果，建议不要使用强制应用字体功能。

我用的EDGE，安装了强制应用字体插件

**Comment by lxgw** [comment]
请您选用其他字体，对给您带来的不便表示歉意。
