### ISSUE TITLE
关于 emoji 的处理

### ISSUE THREAD

**Issue by rlagofla** [lxgw/LxgwWenKai#112]
我在 obsidian 中用了这个字体，我发现这个字体会处理 emoji 的部份

我也不是很懂，但是我感觉大多数字体好像不会处理 emoji，并且不同平台上的 emoji 显示方式也都不同

所以我不知道为什么这个字体出现了有的 emoji 不能显示的情况，我感觉要是可以把 emoji 的部份缺失掉，是不是就可以让下一层字体来接管了呢？

就像 css 中 `font-family: 'LXGW WenKai', 'Apple Color Emoji', serif;` 这样

<img width="64" alt="image" src="https://github.com/lxgw/LxgwWenKai/assets/111237519/c609f166-7ab5-41ef-ae2b-5fae689df00d">

**Comment by lxgw** [comment]
这个字符是 Klee One 原有的，因此文楷保留，您可以利用 FontCreator、FontForge 等软件删去这个字符。

**Comment by yjnu** [comment]
感觉这种可以直接删除或修改，除了显示不统一外，有的直接就是错乱的。比如：emoji 数字 正常的是这样的 1️⃣，而霞鹜文楷中是 

![Image](https://github.com/user-attachments/assets/f2af2549-3a0b-4865-9157-f67815d423b2)

图为 emoji 数字 1，2

**Comment by yjnu** [comment]
> 下个版本将删掉 U+20DD 和 U+20DE 两个字符。

新版删除了这两个字符，好像没有解决问题啊，Emoji 的数字由三个 Unicode 字符组成（数字，emoji 选择变量 FE0F，边框 20E3)，因为数字被定义了，所以不能删除字符，只能定义方形边框 20E3。

PS: 我不是专业的，以上是我的猜测，具体怎么修改还是看落霞孤鹜大佬您 @lxgw

**Comment by lxgw** [comment]
> > 下个版本将删掉 U+20DD 和 U+20DE 两个字符。
> 
> 新版删除了这两个字符，好像没有解决问题啊，Emoji 的数字由三个 Unicode 字符组成（数字，emoji 选择变量 FE0F，边框 20E3)，因为数字被定义了，所以不能删除字符，只能定义方形边框 20E3。

如果其他字体都没有这个问题，那就用其他字体吧，本人能力水平有限。（下个版本把这两个字符加回来？🤔

**Comment by yjnu** [comment]
> 如果其他字体都没有这个问题，那就用其他字体吧，本人能力水平有限。（下个版本把这两个字符加回来？🤔

不关那两个字符的事，应该加回来。

那我学习下怎么解决，有解决方法再告诉您，如果我没搞明白，就不回复了。
