### ISSUE TITLE
「騙」未遵從中國大陸之字形

### ISSUE THREAD

**Issue by saihaze** [lxgw/LxgwWenKai#114]
「騙」字右上方的點與「扁」字不同。「騙」按照日本新字形，未遵從中國大陸新字形。

**Comment by lxgw** [comment]
由于工作量原因，GB 2312 和通规表之外的部分保留 Klee 原有风格。建议您选用[霞鹜文楷 GB](http://github.com/lxgw/lxgwwenkaigb)。

另外，如有修改字形需求请在 #14 反馈，不要另开议题。
