### ISSUE TITLE
字体大小问题

### ISSUE THREAD

**Issue by Huayuluoshi** [lxgw/LxgwWenKai#118]
如图，LXWK：
![截图 2023-07-27 09-57-05](https://github.com/lxgw/LxgwWenKai/assets/117527694/3b0ea79d-b0b9-4fcc-8c88-2fccca5a7afb)
![截图 2023-07-27 09-57-11](https://github.com/lxgw/LxgwWenKai/assets/117527694/80c53fbf-6fc0-496e-87aa-e7c3c4ed964b)
其他字体：
![截图 2023-07-27 10-01-15](https://github.com/lxgw/LxgwWenKai/assets/117527694/cdcfa5e6-5128-405d-8ddc-ebd29c3415c3)
![截图 2023-07-27 10-01-24](https://github.com/lxgw/LxgwWenKai/assets/117527694/590ef70d-d885-4b37-b799-d50557861188)

**Comment by lxgw** [comment]
很抱歉，这个行距问题目前暂无办法修改，建议您选用「固定值」。
