### ISSUE TITLE
字体管理工具中无法展示中文名

### ISSUE THREAD

**Issue by guoyunhe** [lxgw/LxgwWenKai#119]
一些知名的开源中文字体，比如文泉驿和思源，在中文系统的字体管理工具中可以以中文展示其字体名：
![图片](https://github.com/lxgw/LxgwWenKai/assets/5836790/ec61b439-0236-40e4-b7fa-f489c2fc8489)

而霞鹜文楷则始终是以英文展示的：
![图片](https://github.com/lxgw/LxgwWenKai/assets/5836790/67c0bbff-6480-43b6-9a33-112e8ea0db6e)

不知能否优化一下，支持在中文系统中用中文展示字体名？

**Comment by lxgw** [comment]
Windows 下没有问题，其他平台很遗憾恕无法复现。
