### ISSUE TITLE
能否把所有作者的字体 做一个合集 可以一键下载的内种

### ISSUE THREAD

**Issue by RainPPR** [lxgw/LxgwWenKai#121]
真的超爱作者的字体（我电脑上除了 Windows 自带的就是作者的了）

能否做一个合集，把作者的所有字体放在一起，不一定要实时更新的，就是可以一键下载作者的 all 字体的内种【只是作者38个仓库（截至到20230821）我实在是找不过来，也不知道哪些是新版，哪些是旧版的】

麻烦作者了

**Comment by lxgw** [comment]
很抱歉，由于字体文件比较多，再加上精力有限，暂时不会考虑提供所有字体的打包一键下载。不过您可以进入[开源字体一览表（图文版）]()查看本人的开源字体列表，或者进入本人的[永硕网盘]()下载大部分字体。

祝您使用愉快！

**Comment by RainPPR** [comment]
好的谢谢


| |
RainPPR
|
|
***@***.***
|
---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2023年8月22日 01:02 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***> ,
***@***.***> |
| 主题 | Re: [lxgw/LxgwWenKai] 能否把所有作者的字体 做一个合集 可以一键下载的内种 (Issue #121) |

很抱歉，由于字体文件比较多，再加上精力有限，暂时不会考虑提供所有字体的打包一键下载。不过您可以进入开源字体一览表（图文版）查看本人的开源字体列表，或者进入本人的永硕网盘下载大部分字体。

祝您使用愉快！
