### ISSUE TITLE
FastGPT 官方文档已接入 LXGW WenKai

### ISSUE THREAD

**Issue by yangchuansheng** [lxgw/LxgwWenKai#123]
[FastGPT 官方文档](https://doc.fastgpt.run/)已接入该字体，感谢作者！🙏🙏🙏

**Comment by lxgw** [comment]
感谢您的支持，尽管您用的可能不是最新版（如下图「编」字）。
![image](https://github.com/lxgw/LxgwWenKai/assets/51902309/e542d871-4e0a-4ae3-963d-24a694468c81)
