### ISSUE TITLE
MacOS 系统下直排直角引号等标点未正确旋转

### ISSUE THREAD

**Issue by hut36** [lxgw/LxgwWenKai#124]
如图所示。
<img width="742" alt="Screen Shot 2023-09-22 at 11 01 29" src="https://github.com/lxgw/LxgwWenKai/assets/73904/6e9a790d-8d03-43ed-9725-60711bd329cb">

参照 Songti.ttc, 在 vert lookups 加入如下两个特性：

<4,0> DFLT{dflt} arab{dflt} bopo{dflt} cyrl{dflt} grek{dflt} hani{dflt} kana{dflt} latn{dflt} mong{dflt} tibt{dflt} yi  {dflt}
vrt2 DFLT{dflt} arab{dflt} bopo{dflt} cyrl{dflt} grek{dflt} hani{dflt} kana{dflt} latn{dflt} mong{dflt} tibt{dflt} yi  {dflt}

之后，可以正确旋转直角引号等标点。

**Comment by lxgw** [comment]
Windows 上的 Office 没有这个问题。

**Comment by lxgw** [comment]
Windows 上的 Office 没有这个问题。

由于本人没有 Mac OS 设备，所以此条问题恕无法复现，抱歉。

如您介意，可更换其他同类字体。

**Comment by lxgw** [comment]
Windows 上没有这个问题。

由于本人没有 Mac OS 设备，所以此条问题恕无法复现，抱歉。（不知您用的是什么软件？

如您介意，可更换其他同类字体。
