### ISSUE TITLE
三种字重差距不够明显

### ISSUE THREAD

**Issue by kooriookami** [lxgw/LxgwWenKai#125]
霞鹜文楷 Light、Normal、Bold 示例：
![微信图片_20231009111002](https://github.com/lxgw/LxgwWenKai/assets/38392315/a8d8471b-f67b-43ff-9177-c2992fc58483)
这三种字重的差距比起下图思源黑体的字重差异不明显。感觉 Light 可以更细，Bold 可以更粗。

思源黑体 Light、Normal、Bold 示例：
![image](https://github.com/lxgw/LxgwWenKai/assets/38392315/50d5b1a2-3a3d-4033-a476-616e92cda66a)

**Comment by lxgw** [comment]
很抱歉，由于本人能力有限，恕无法满足您的要求。

本人曾开过 #37 这个 issue，用以征集各个字重的命名方式，但由于 Light、Regular、Bold 这样的字重命名已经持续了多个版本，如果改的话可能会引起混乱，于是一直保持这样的字重命名方式，#37 这个 issue 也关闭了。

如您介意，可更换其他字体。再次为这款字体给您带来的不便表示歉意。

**Comment by kooriookami** [comment]
没有关系啦，这只是我的一个想法，字体本身是很好的。

**Comment by zengfanfan** [comment]
你好，如果只是命名上的困扰，可否在不改动 Light、Regular、Bold 的情况下增加其他字重呢？
比如 ExtraBold、Heavy、Black……

bold真的不够粗啊……

某免费字体的命名，仅作参考：
![image](https://github.com/lxgw/LxgwWenKai/assets/8079595/8b4e5dac-a4fd-472e-bead-7458822f00a7)

@lxgw

**Comment by lededev** [comment]
希望能够增加中黑、中粗字重，调整粗体字重。

**Comment by lxgw** [comment]
下个版本会将 Bold 改回 Medium。
