### ISSUE TITLE
Concerns Regarding Copyright Issues in AI Training

### ISSUE THREAD

**Issue by Honoka55** [lxgw/LxgwWenKai#128]
I would like to express concerns regarding potential copyright infringement related to the font LXGW WenKai during its AI training process, specifically referencing the usage of the commercial font [Tsanger Jin Kai](http://tsanger.cn/product/7), as mentioned by @lxgw in a QQ group discussion.

It is essential to address this issue promptly to ensure that the font’s creation process respects the intellectual property rights of font creators. Transparency in the font creation process, especially concerning the incorporation of commercial fonts within AI training datasets, is essential to prevent any potential legal implications and maintain ethical practices within the open-source community.

I kindly request clarification or further discussion on this matter to ensure that LXGW WenKai was created ethically and in compliance with copyright and generative artificial intelligence regulations.

Thank you for your attention and prompt action on this issue.

**Screenshot of the QQ discussion:**

![image](https://github.com/lxgw/LxgwWenKai/assets/71088406/1a72202a-5b55-4b20-a943-5a474e378e7f)

**Screenshot transcript:**

> (Others’ inquiry) So did you include them or not?
> I included some glyphs generated with Jin Kai and some glyphs generated with Source Han Sans (*in LXGW WenKai*).

**Comment by lxgw** [comment]
Thank you for your concern.

In order to address the potential copyright infringement issues arising from the artificial intelligence training process, an emergency update to clean up all the suspicious glyphs will be released soon and all the releases which include suspicious glyphs will be removed.

**Comment by xen0n** [comment]
Thanks for raising the concern and helping keep the ecosystem healthy compliance-wise!

I've just removed old versions of `lxgw-wenkai` from the main Gentoo repository, so mirrored assets should disappear across the mirrors after a while.
