### ISSUE TITLE
旧release版本的字体文件不见了

### ISSUE THREAD

**Issue by Enter-tainer** [lxgw/LxgwWenKai#129]
as title， https://github.com/OI-wiki/OI-wiki/blob/05d677c44a1b9490ffa51d6b6b7e34323fd22a9d/.github/workflows/build-pdf-typst.yml#L39C56-L39C56 这个 ci 任务会每次从 release 下载 lxgw wenkai，但是最近突然挂掉了。观察 release 页面，发现旧版本也确实没有字体文件了。请问这个是期望的行为吗

**Comment by lxgw** [comment]
由于 #128 的原因，之前涉及 AI 生成字形的历史字体文件均作删除处理。

**Comment by lxgw** [comment]
后续会在圣诞节前后发布 v1.312 更新，届时 v1.311 版本的字体文件也会删除。
