### ISSUE TITLE
calt、salt OpenType 特性失效

### ISSUE THREAD

**Issue by Mjzsl123-github** [lxgw/LxgwWenKai#132]
我知道作者知道这个有问题，但好像能修。
![image](https://github.com/lxgw/LxgwWenKai/assets/110514823/374bee6d-ef27-45ff-90bf-b11fe63bbd50)
字体更新之后，双层a字形的名称从a.salt变成了glyph33716，居中冒号的字形好像是没了。于是两个lookup就出问题了。把名称修好之后，冒号居中似乎恢复正常，salt由于不知道怎么调出来还不清楚。

**Comment by lxgw** [comment]
请问您是用什么方法修的？

再用 FontForge 打开再导出一遍，看看还能不能生效。

**Comment by Mjzsl123-github** [comment]
> 请问您是用什么方法修的？
> 
> 在 v1.312 版本字体的基础上把 v1.315 新增的字符加进去再导出试试看。
> 
> 再用 FontForge 打开再导出一遍，看看还能不能生效。

这几天没有看回复，抱歉。这里是用FontCreator进行的操作。至于重新尝试，现在因为不在设备附近而暂时无法做到，之后会告知您结果。希望这条回复没有打扰到您。

**Comment by lxgw** [comment]
排查出来了，是 FontCreator 的原因，需要每次合并的时候在 FontCreator 把 lookup 加回来。
