### ISSUE TITLE
大佬，霞鹜文楷系列字体不支持360安全浏览器和360极速浏览器，用别的字体就可以，详情请看链接。

### ISSUE THREAD

**Issue by Jimmy20220531** [lxgw/LxgwWenKai#133]
网页字体设置不统一的问题，很久了。_360社区
https://bbs.360.cn/thread-16106658-1-1.html
是字体问题，360浏览器不支持霞鹜文楷系列字体，换成别的就可以。

**Comment by lxgw** [comment]
请选用其他字体，对这款字体给您带来的不变表示歉意。

**Comment by lxgw** [comment]
对这款字体给您带来的不便表示歉意，由于本人能力有限，目前无法解决这个问题，请您选用其他字体。
