### ISSUE TITLE
更新MAC安装指令

### ISSUE THREAD

**Issue by Jagerx** [lxgw/LxgwWenKai#139]
https://github.com/Homebrew/homebrew-cask-fonts 已弃用

用brew tap homebrew/cask-fonts && brew install font-lxgw-wenkai会提示错误：Error: homebrew/cask-fonts was deprecated. This tap is now empty and all its contents were either deleted or migrated.

修改为：brew install --cask font-lxgw-wenkai

**Comment by zhuxining** [comment]
能否将 font-lxgw-wenkai-screen 也加入 brew 中下载
