### ISSUE TITLE
cmap 似乎损坏了

### ISSUE THREAD

**Issue by Mistsink** [lxgw/LxgwWenKai#141]
使用python程序使用该字体是需要查询cmap来检查是否支持某个字符，但是检测时发现cmap损坏了，程序一直运行错误。
下面的程序结果验证了cmap的损坏情况：
```bash
$ python -m ots LXGWWenKai-Regular.ttf 
ERROR: cmap: Failed to read segment start range 441
ERROR: cmap: Failed to parse format 4 cmap subtable 0
ERROR: cmap: Failed to parse table
Failed to sanitize file!
```

**Comment by spencer246** [comment]
`fontTools.ttLib` cannot parse the `cmap` table as well.

Interestingly, `fontTools` has no problem in parsing the TC version of the font, although these fonts are released on the same day.

**Comment by Mistsink** [comment]
非常感谢，期待您的消息
