### ISSUE TITLE
Bold is hardly bold

### ISSUE THREAD

**Issue by DutchPete** [lxgw/LxgwWenKai#142]
I love your font and am using it in my note-taking app, which means a lot of text.
However, the difference between bold and regular is very slight.

![image](https://github.com/user-attachments/assets/a7fd92e3-2860-441d-8586-2ede0768a495)

Is there a way you could improve that?

**Comment by lxgw** [comment]
Sorry, but I couldn't improve that.

**Comment by DutchPete** [comment]
No, it is not much better than WenKai, which what I will stick with.
Thank you for your quick response.

**Comment by lxgw** [comment]
The Bold weight will be changed into Medium next release.

**Comment by DutchPete** [comment]
Will that make **bold** text more pronounced?

**Comment by lxgw** [comment]
> Will that make **bold** text more pronounced?

Bolding will be implemented directly by the system.

**Comment by DutchPete** [comment]
OK. Please let me know when the next release it available so I can download it.
