### ISSUE TITLE
能收录编程常用的symbol吗？

### ISSUE THREAD

**Issue by SadSock** [lxgw/LxgwWenKai#143]
![图片](https://github.com/user-attachments/assets/e8371d03-d8f2-4bfd-a983-59e98890ddfe)

写code很好看，就是symbol都乱码了。

推荐一集成一下这个项目

https://github.com/ryanoasis/nerd-fonts

谢谢🙏

**Comment by lxgw** [comment]
抱歉，没有这个计划，不过本字体是开源的，如果有能力的话可以自行修改。

**Comment by Yikai-Liao** [comment]
https://github.com/Yikai-Liao/LxgwWenKaiNerdFont/releases

@SadSock  我用 nerd-fonts 这个项目为落霞孤鹜文楷补全了nerd font，是通过github actions每天检测落霞孤鹜文楷有没有发布新版本，如果有就自动patch然后发布。

今天刚把github actions 的流程跑通，目前还不确定有没有bug，不过我已经用上了。之前我在github上看到有别人发布，但都是patch 一次就不维护了，而且字重不全，我这次把所有字重都做了patch。
