### ISSUE TITLE
Ubuntu24.04 无法安装

### ISSUE THREAD

**Issue by FallingSakura** [lxgw/LxgwWenKai#144]
RT
无论以文件形式安装还是在GUI中安装，都无效，字体软件不显示它为已安装，并且软件无法识别。

**Comment by lxgw** [comment]
本字体的其他版本（如 GB 版、TC 版）是否可以安装？

**Comment by FallingSakura** [comment]
> 本字体的其他版本（如 GB 版、TC 版）是否可以正常安装？
> 
> 其他字体是否可以正常安装？
> 
> 或许更新字体缓存可以解决问题，但是我的 Xubuntu 版本是 22.04，可能会跟 24.04 有差别。

我也不知道怎么它就装上了，我把它放在 /usr/share/fonts/truetype/custom 文件夹后就没再管过。

后面因为 Unicode 字符编码问题我给系统改成英文模式了，然后经历了几次重启，我不知道是因为重启还是因为改系统语言，总之现在问题解决了。
