### ISSUE TITLE
您好, wenkai-mono这款字体为什么在mac的fontbook里面显示不是固定宽度呢?

### ISSUE THREAD

**Issue by liuyinz** [lxgw/LxgwWenKai#150]
我想在其他软件中使用这款字体, 但是被告知只支持固定宽度的字体, 我才发现wenkai-mono被识别不是固定宽度

**Comment by lxgw** [comment]
[LXGWWenKaiMono-Regular.zip](https://github.com/user-attachments/files/17179629/LXGWWenKaiMono-Regular.zip)

这个能否被识别？

**Comment by liuyinz** [comment]
这个可以了, 不过只有regular,没有light之类的,我原来安装的还是1.33 brew的版本.

**Comment by liuyinz** [comment]
@NightFurySL2001 你这个可以了,可以正确被识别. 是更新到1.500版本就行了吗还是要等新的版本呢? 我这边brew的源还停留在1.33

**Comment by NightFurySL2001** [comment]
可以先暂时使用这个，我会和lxgw沟通下一版更新这个问题。brew方面并不是lxgw维护的，可能要看是谁提交上去的。

**Comment by lxgw** [comment]
> @NightFurySL2001 你这个可以了,可以正确被识别. 是更新到1.500版本就行了吗还是要等新的版本呢? 我这边brew的源还停留在1.33

后续会发 v1.501，修复这个问题。

**Comment by liuyinz** [comment]
好的, 多谢多谢.

**Comment by lxgw** [comment]
> 我下载了最新的release ```lxgw-wenkai-v1.521```
> 我发现它似乎还是不会被程序识别为等宽字体，eg. kitty (在 kitten choose-fonts 里没有这个)
> 我通过查询似乎 monospace 的 font 的 spacing是 100(i)(s) 
> 这可以通过```fc-scan```来查询
> ```
> % fc-scan /usr/share/fonts/TTF/UbuntuMonoNerdFontMono-Regular.ttf | grep spacing   
> 	spacing: 100(i)(s)
> ```
> ```
> % fc-scan ./LXGWWenKaiMono-Light.ttf | grep spacing   
> zsh: done       fc-scan ./LXGWWenKaiMono-Light.ttf | 
> zsh: exit 1     grep spacing
> ```
> 似乎同样是 monospace 字体，可是 ubuntumono 有这个属性，而 LXGWWenKaiMono 没有
> 当然我对这个了解的也不透彻，见谅，谢谢～

可能是因为「⸺`U+2E3A`」和「⸻`U+2E3B`」这两个字符吧。
