### ISSUE TITLE
是否可以考虑单独发布西文字体？

### ISSUE THREAD

**Issue by yeezylife** [lxgw/LxgwWenKai#151]
目前替换了系统的 微软雅黑/微软雅黑light/微软雅黑bold  但是有些标题的英文部分还是Segoe UI，我估计需要把系统默认的英文字体也替换掉才能正常显示。。。

可不可以考虑单独发布西文字体。。。

**Comment by lxgw** [comment]
这种需求还是第一次见。。。

您可以自行提取西文部分制作单独的西文字体，惟需注意字体名称中不得包含保留名称。
