### ISSUE TITLE
等宽字体的粗体字符与普通字符大小不一致。

### ISSUE THREAD

**Issue by yuhoocom** [lxgw/LxgwWenKai#154]
`落霞孤鹜等宽`及分支的`LXGW Bright Code`字体因为粗体字符与普通字符大小不同，造成在一些文本编辑器上**不能垂直对齐**的情况。
具体情况请看https://github.com/zufuliu/notepad4/issues/935

**Comment by lxgw** [comment]
由于 v1.500 版本起原粗体调整为中粗体，因此所有粗体都由系统直接渲染加粗，在 Windows 下会出现稍微加宽的情况。但是，这种调整是因为大多数用户认为原来的粗体不够粗，与常规字重分辨不清才做出的考量。如您介意宽度问题，可以选用 v1.500 以前的版本。在此对这款字体给您带来的不便表示歉意。

**Comment by yuhoocom** [comment]
感谢告知😁
