### ISSUE TITLE
「ㄐ(ji)」能否向左推约60 points?

### ISSUE THREAD

**Issue by jeffreyxuan** [lxgw/LxgwWenKai#17]
感谢Lxgw的辛苦制作, 很喜欢这个优雅的字型, 您补字神速也是令人刮目相看. 尤其是看到0.303版有补上ㄅㄆㄇ注音字型, 实在让人感激, 海外中文教学常常需要制作汉语拼音与注音的教材. 霞鹜文楷繁简体兼备且美观, 许多汉语老师都很赞赏.

小弟目前在「汉语拼音及注音在线工具 ToneOZ.COM 」上面实作了0.303版霞鹜文楷woff2 webfont, 效果令人满意, 这是一个能自动校正多音字在中文上方标注汉语拼音的工具, 在线使用免费免安装. 有一个小建议: 注音符号「ㄐ(ji)」是否能向左推约60 points? 因为注音教学时的习惯是直式排列, 并且会与韵母「一(yi)」或「ㄩ(yu)」搭配. 目前的「ㄐ」在视觉效果上重心稍微偏右, 与思源黑体或者标楷体比对时可以观察到.

本想尝试pull request, 但手边工具只有fontcreator试用版. 以下附上效果图解, 提供您下一版调整的参考. 再次感谢您的优秀作品.

![blog20210506-1](https://user-images.githubusercontent.com/14179988/117244756-f84e7080-ae7c-11eb-8819-8d47b08c3069.jpg)

![blog20210506-2](https://user-images.githubusercontent.com/14179988/117246785-9263e800-ae80-11eb-8ae2-0b576196dfa4.jpg)

![blog20210506-3](https://user-images.githubusercontent.com/14179988/117246799-97c13280-ae80-11eb-8bfb-73d87e18ec1c.jpg)

![blog20210506-4](https://user-images.githubusercontent.com/14179988/117246811-9c85e680-ae80-11eb-9e4f-a40246d8bb3b.jpg)

**Comment by lxgw** [comment]
https://github.com/lxgw/LxgwWenKai/releases/tag/v0.312
