### ISSUE TITLE
“凊”字 (U+51CA) 的宽度与众不同

### ISSUE THREAD

**Issue by Ming-Hua** [lxgw/LxgwWenKai#19]
首先感谢您对这款字体的补全工作？

我在 LibreOffice 中试用这套字体（0,323 版本，Regular 字重）时，发现凊 (U+51CA) 这个字（千字文里用的一个字）的宽度似乎比其他所有字和中文标点的宽度都略窄一些，导致排版上出现不对齐。参见附的截图，这是 12 pt 字体在 LibreOffice 7.0.6 中的效果。

没有安装原 Klee One 字体，不清楚是霞鹜文楷特有的问题还是从 Klee 继承来的。也尚未在其他应用程序中测试，但如有必要我很乐意做进一步测试。

![image](https://user-images.githubusercontent.com/5502125/119210825-12c15480-bae1-11eb-8881-17481422e08a.png)

**Comment by lxgw** [comment]
0.325 版本已更新。

**Comment by Ming-Hua** [comment]
下载了 0.325 版，确认已修复。感谢！
