### ISSUE TITLE
字形建议：乐

### ISSUE THREAD

**Issue by noka233** [lxgw/LxgwWenKai#2]
『乐』字第一笔的丿斜度很大，且上半部分大于下半部分，显得在整体版面阅读中很突兀
(⌯꒪꒫꒪)大大能采纳就好了

**Comment by noka233** [comment]
感觉上其实把前两笔占的地方缩小，另一部分相对占多一点地方，看起来就会好很多，跟第一笔的撇也没太大关系

**Comment by lxgw** [comment]
![ydQvLt.png](https://s3.ax1x.com/2021/02/09/ydQvLt.png)

这样可以吗？

**Comment by noka233** [comment]
对，这样就比较舒服了
