### ISSUE TITLE
希望可以支持英文等宽

### ISSUE THREAD

**Issue by mouyase** [lxgw/LxgwWenKai#23]

**Comment by lxgw** [comment]
https://github.com/lxgw/LxgwWenKai/releases/tag/v1.004-mono-beta

已经有了等宽测试版。

**Comment by dawncold** [comment]
我昨天在manjaro中安装了非等宽的字体，Chrome中把除了等宽字体外的三种都选上了lxgw，发现看英文的时候已经比较等宽了

这是我的截图（非等宽字体）
![1_0OxqzA27sbQClzhAa6T9Zg](https://user-images.githubusercontent.com/502856/126090904-31280022-70e6-4d7e-8e34-c21e0943ab87.png)

**Comment by SeaHOH** [comment]
v1.005

许多字符 (主要是小写字母) 占宽过于饱满，在字号小于 18 pt 时会粘连，以致一眼望去不够明晰。
以下是 Windows 7 Notepad2 中的 16 pt 效果：
![wkm](https://user-images.githubusercontent.com/8470820/126315740-96bb548d-6b3f-4615-8a4b-386e06c7b378.png)

**Comment by SeaHOH** [comment]
@lxgw v1.007 仍然会粘连，请问这个问题能修复吗？

**Comment by jeffreyxuan** [comment]
@lxgw  回报:v1.007 等宽版本, 汉语拼音āáǎà ēéěè īíǐì ōóǒò ūúǔù ǖǘǚǜ ńňǹ ḿ的左右位置与原始字母 "aeioumn"比较, 每个有调号的汉语拼音都有不同程度的位移, 而且 Light Regular Bold 位移程度均不同, 有些往左偏有些往右偏. 偏移也不同, 8pt ~ 2pt都有.
