### ISSUE TITLE
webfont npm 包

### ISSUE THREAD

**Issue by chawyehsu** [lxgw/LxgwWenKai#24]
https://github.com/chawyehsu/lxgw-wenkai-webfont

有需要可以使用，我用 ttf2woff2 工具转的格式，不清楚会不会产生问题，测试挺正常。

**Comment by lxgw** [comment]
感谢提供，可以用在我的 lxgw.github.io 上了。

**Comment by Goose-Bomb** [comment]
你好 可以提供lite版本的web字体吗

**Comment by chawyehsu** [comment]
> 你好 可以提供lite版本的web字体吗

可以，我这两天更新下，顺便写个脚本后续自动更新。

**Comment by chawyehsu** [comment]
@Goose-Bomb Lite 版本 https://www.npmjs.com/package/lxgw-wenkai-lite-webfont
另外 TC 版也分离出来单独提供了 https://www.npmjs.com/package/lxgw-wenkai-tc-webfont

新版 webfont 做了 subset 处理，所以在常用字的加载上，原版和 Lite 版的差距应该不会很大的，都是按需加载。

**Comment by Goose-Bomb** [comment]
> @Goose-Bomb Lite 版本 https://www.npmjs.com/package/lxgw-wenkai-lite-webfont 另外 TC 版也分离出来单独提供了 https://www.npmjs.com/package/lxgw-wenkai-tc-webfont
> 
> 新版 webfont 做了 subset 处理，所以在常用字的加载上，原版和 Lite 版的差距应该不会很大的，都是按需加载。会比旧版整个加载要好一点。

十分感谢！

**Comment by oldherl** [comment]
建议将这个CDN的信息增加到「下载字体」一段中，不然一般人可能看不到

**Comment by guuzaa** [comment]
这款字体很好看，感谢作者的慷慨！我自己的博客也用了这款字体，符合我的审美。但是，有一个问题想要请教一下，有没有计划把这款字体提交到 Google Font 里面去呢？这样受众更广，更利于推广。
https://github.com/google/fonts/blob/main/CONTRIBUTING.md

**Comment by colgin** [comment]
> 这款字体很好看，感谢作者的慷慨！我自己的博客也用了这款字体，符合我的审美。但是，有一个问题想要请教一下，有没有计划把这款字体提交到 Google Font 里面去呢？这样受众更广，更利于推广。 https://github.com/google/fonts/blob/main/CONTRIBUTING.md

看了一下已经提交mr 了 https://github.com/google/fonts/issues/4802#issue-1274451024

**Comment by cxw620** [comment]
关于[chawyehsu](https://github.com/chawyehsu)制作的webfont, 我向cdnjs提了pr, 目前merge了, 国内已有镜像
https://cdn.staticfile.org/lxgw-wenkai-webfont/1.6.0/style.css
https://cdn.staticfile.org/lxgw-wenkai-screen-webfont/1.6.0/style.css
目前只有这两个, 其他的没提交

**Comment by Santcu** [comment]
引入CSS导致部分情况下中英文标点错乱
使用字体文件
![230848814-30746fd8-b7ef-4b35-ad76-4ad126b7b085](https://github.com/lxgw/LxgwWenKai/assets/122136747/be1e4476-bd7b-4ef3-a5eb-ba0186dffbf1)
引入CSS文件
![230848903-ad15ae46-696e-4239-8b34-a8f878c7b109](https://github.com/lxgw/LxgwWenKai/assets/122136747/e17d8e45-8fa7-4e88-b5a1-cce6be63d883)

**Comment by KonghaYao** [comment]
中文网字计划提供了 霞鹜文楷 的免费CDN，如需使用，可以在网站上直接加入链接使用。详见 https://chinese-font.netlify.app/fonts/lxgwwenkai/lxgwwenkai-light/

![image](https://github.com/lxgw/LxgwWenKai/assets/68177907/b3336f68-ea68-4fc6-8350-bf0a394e3b0d)

![image](https://github.com/lxgw/LxgwWenKai/assets/68177907/58ef742d-2a40-44e9-b2f8-585415255383)

**Comment by CMBill** [comment]
前面提供的似乎版本都比较老了，所以我用中文网字计划的分包工具对最新版本的字体分了包放在GitHub仓库里了，有需要的可以直接用，也可以克隆到自己的存储中

霞鹜文楷：[https://github.com/CMBill/lxgw-wenkai-web](https://github.com/CMBill/lxgw-wenkai-web)
霞鹜文楷屏幕阅读版：[https://github.com/CMBill/lxgw-wenkai-screen-web](https://github.com/CMBill/lxgw-wenkai-screen-web)
霞鹜文楷 GB：[https://github.com/CMBill/lxgw-wenkai-gb-web](https://github.com/CMBill/lxgw-wenkai-gb-web)
霞鹜文楷 TC：[https://github.com/CMBill/lxgw-wenkai-tc-web](https://github.com/CMBill/lxgw-wenkai-tc-web)

**Comment by mobeicanyue** [comment]
> 前面提供的似乎版本都比较老了，所以我用中文网字计划的分包工具对最新版本的字体分了包放在GitHub仓库里了，有需要的可以直接用，也可以克隆到自己的存储中
> 
> 霞鹜文楷：https://github.com/CMBill/lxgw-wenkai-web 霞鹜文楷屏幕阅读版：https://github.com/CMBill/lxgw-wenkai-screen-web 霞鹜文楷 GB：https://github.com/CMBill/lxgw-wenkai-gb-web 霞鹜文楷 TC：https://github.com/CMBill/lxgw-wenkai-tc-web

可用 多谢分享！
