### ISSUE TITLE
版本号是否需要降级调整？

### ISSUE THREAD

**Issue by lxgw** [lxgw/LxgwWenKai#26]
由于此款字体仍存在大量的问题，如字形突兀不和谐等，不适合作为 1.x 正式版。

下次更新时考虑 tag 版本号降至 v0.404，届时已经发布的 v1.0 ~ v1.003 版本将调整为 v0.400 ~ v0.403 版本。

是否需要这样调整版本号，给这款字体一个完善的空间？
没有降过 tag 的版本号，这样做相当于撤掉了 v1.0 及之后的版本。

**Comment by Chocorenka** [comment]
支持一下，为了让字体更加完善，个人觉得可以降一下，版本号无所谓。
不过其实不降也没关系，毕竟1.0可以看做是一个阶段性调整较完善的版本也没有问题。
甚至很多人都是从1.0开始发布版本的，所以不必特别纠结版本号。

**Comment by OYcedar** [comment]
不必降版本，正式版一样可以修修补补，而且正式版也是可以代表更新变慢的意思。

**Comment by daorren** [comment]
如果作者比较纠结的是版本号的话，可能是因为大家默认考虑的是SemVer。但其实还有别的版本号命名方式，比如[Calendar Versioning](https://calver.org/#scheme)，简单来说就是将日期加入版本号中。
比如Ubuntu的版本号，16.04.<micro>，16表示16年发布，04表示4月。
可以参考[self-host sentry 博客](https://blog.sentry.io/2020/06/22/self-hosted-sentry-switching-to-calver)，文中提到，本来该版本号已经到了10作为major，但是因为他们考虑到和商用版sentry版本混淆、自己的release节奏等原因，切换到了calver。
如果作者也可以有按日期的周期性发布的话，其实也可以迁移到calver上面来

**Comment by troublewind** [comment]
麻烦问下v1.100怎么没有文楷UI，很喜欢这个字体当作阅读字体，谢谢

**Comment by lxgw** [comment]
> 麻烦问下v1.100怎么没有文楷UI，很喜欢这个字体当作阅读字体，谢谢

文楷 UI 打算另库维护，另外会考虑更名。
