### ISSUE TITLE
《铜豌豆 Linux》为该字体，制作了一个 deb 软件包

### ISSUE THREAD

**Issue by atzlinux** [lxgw/LxgwWenKai#27]
您好！
   这款字体不错，《铜豌豆 Linux》项目为该字体制作了一个 deb 格式的软件包，可以用于 Debian 系 Linux 发行版安装。

《铜豌豆 Linux》软件源：
https://www.atzlinux.com/allpackages.htm

字体软件包名称为： fonts-cjk-zh-lxgw-wenkai 

不知道能否在你们项目页面的下载信息处，加上这个信息，方便大家直接安装 deb 软件包？

**Comment by lxgw** [comment]
可以随着字体 Release 的更新而更新吗？

**Comment by atzlinux** [comment]
目前还无法做到完全自动化升级更新 deb 软件包，需要人工处理。

铜豌豆 项目计划每 三个月 更新该字体软件包。如果期间有特别重要的更新，也可以通知我们手工处理。

**Comment by lxgw** [comment]
目前已经更新到 v1.0p4，并增加等宽字体。

**Comment by atzlinux** [comment]
> 目前已经更新到 v1.004，并增加等宽字体。

请问下字体的 ttf 文件，可以通过 github 上的源代码用脚本或者命令编译生成吗？

如果可以的话，就比较好利用打包的脚本生成新版本的  deb 软件包。

**Comment by lxgw** [comment]
不能。目前只有现成的 ttf 文件，以及部分字的 FontCreator 项目文件。

**Comment by atzlinux** [comment]
> 不能。目前只有现成的 ttf 文件，以及部分字的 FontCreator 项目文件。
> 
> 所以只能手动打包了。

是否方便把 ttf 文件，直接放到 git 仓库里面提交？
这样的话，可以直接用  git pull 命令把最新的字体文件拖下来，也非常有利于自动化制作新版本的  deb 软件包。

**Comment by lxgw** [comment]
> > 不能。目前只有现成的 ttf 文件，以及部分字的 FontCreator 项目文件。
> > 
> > 所以只能手动打包了。
> 
> 是否方便把 ttf 文件，直接放到 git 仓库里面提交？
> 这样的话，可以直接用  git pull 命令把最新的字体文件拖下来，也非常有利于自动化制作新版本的  deb 软件包。

#4

**Comment by txyyh** [comment]
每个 releases 的ttf文件名称都一致，可以用latest抓取最新字体啊

**Comment by atzlinux** [comment]
铜豌豆的 deb 包，打包脚本放在码云仓库：

https://gitee.com/atzlinux/fonts-cjk-zh-lxgw-wenkai/tree/master/debian


欢迎提交实现该功能的脚本过来。


在 2021/7/24 上午6:18, 童心音乐会 写道:

**Comment by txyyh** [comment]
@atzlinux 我不撤了吗。。。

**Comment by atzlinux** [comment]
> @atzlinux 我不撤了吗。。。

? 什么意思？
