### ISSUE TITLE
【字体反馈】图中的门字看着特别怪，好像变成异形字了

### ISSUE THREAD

**Issue by OYcedar** [lxgw/LxgwWenKai#29]
![1696CC93-5144-415B-BABD-AEAE6EE99A63](https://user-images.githubusercontent.com/13297960/126268435-e0c411d6-a223-4c40-809a-a1540ef49f5b.png)
不知道是不是识别问题，左边是系统原字体，右边是1.004字体，在手机上用magisk刷了字体后用多看阅读看的效果。
使用其他字体看，门字也是正常的。

**Comment by lxgw** [comment]
与 Magisk 模块有关的问题，不建议在 issue 上反馈。
