### ISSUE TITLE
“莫”字的字形问题

### ISSUE THREAD

**Issue by gingerbreap** [lxgw/LxgwWenKai#30]
![image](https://user-images.githubusercontent.com/27958821/127455477-cb225850-5041-4e64-83b8-5744ca179f37.png)
这应该不是简体中文的标准字形吧……

**Comment by gingerbreap** [comment]
不知道为什么没法再复现 先close

**Comment by lxgw** [comment]
「莫」字没问题，您可能是在哪看到的「莫」打成「茣」的吧。
