### ISSUE TITLE
这款字体安装后，为什么没办法在Gvim中找到这种字体

### ISSUE THREAD

**Issue by hhs66317** [lxgw/LxgwWenKai#31]
环境：
- Windows 10
- Gvim 8.2
- LXGWWenKaiMono-Regular.ttf  1.005

下载字体并安装后，在gvim中找不到该字体，无法正常使用

**Comment by lxgw** [comment]
可能跟 Panose 有关，Gvim 只识别纯等宽字体，然而我尝试在 Panose 中把属性改为等宽字体，导出后发现字体查看器中显示效果异常，就没改 Panose 信息。

**Comment by hhs66317** [comment]
有办法解决么？
或者提供一个修改了属性的版本，我尝试下？

**Comment by lxgw** [comment]
> 有办法解决么？
> 或者提供一个修改了属性的版本，我尝试下？

https://lxgw.lanzouw.com/imDlotlyzkj

**Comment by hhs66317** [comment]
非常感谢！修改了等宽属性之后，再Gvim中确实可以使用这款字体了，而且效果很棒！

![image](https://user-images.githubusercontent.com/3916247/132450142-6e93bc6e-db3e-421f-8885-c224f1907f57.png)

**Comment by hhs66317** [comment]
我用记事本做了个简单的测试发现，同样的文字内容，都是从剪切板中粘贴的，使用雅黑是正常显示的，使用了【等宽属性】的霞鹭字体后，除了文字间距存在问题，竟然连显示的中文内容也变调了，这个有些奇怪。

不过好在Gvim中是没有问题的，对我来说就够了。

![image](https://user-images.githubusercontent.com/3916247/132450607-34d0fc45-ad86-4522-9e01-73be8a16a9d9.png)
