### ISSUE TITLE
“比” “商” 等简繁异体字有待调整。

### ISSUE THREAD

**Issue by RuikangSun** [lxgw/LxgwWenKai#32]
今天在猫啃网浏览这个字体时注意到，还有一些简繁异体字的书写方式不符合简体字规范。例如“商”字下应为点而非竖折，“比”左侧应为竖提。
如果可以的话，能否在调整异体字的过程中，整理出一份从日韩文字开发简体字时需要修改的异体字清单？以便后人开发简体字体。

**Comment by lxgw** [comment]
猫啃网中用于预览的字体是旧版，目前「商」字早已将「儿」改作「八」，「比」字视乎风格不作改动。

**Comment by RuikangSun** [comment]
> 
> 
> 猫啃网中用于预览的字体是旧版，目前「商」字早已将「㇒㇄」改作「㇒㇔」，「比」字视乎风格不作改动。建议下载最新版 1.005 版。
> 
> 对于「需要修改的异体字清单」，可参考本项目的更新日志。

如果可以的话，最好能联系猫啃网那边把预览改一下。用户选择字体，可能仅通过预览来判断本地化程度。
