### ISSUE TITLE
竖排时垂直尺寸 (Vertical Metrics) 的问题

### ISSUE THREAD

**Issue by lhy7889678** [lxgw/LxgwWenKai#34]
在 LaTeX 中，使用 LuaTeX-ja 进行竖排时，霞鹜文楷字体的“位置”出现问题。目前尝试过的其他知名开源字体以及 Klee One 均无此问题。在与其他字体合用或进行标点调整时，问题显现得更加明显。如图所示：

![Screenshot_20210827_103651](https://user-images.githubusercontent.com/66711810/131064960-c7ff692d-2308-4dd5-abd2-8c552c6876cd.png)

其中，从右到左分别为 Noto Serif CJK SC、一点明朝、霞鹜文楷、霞鹜文楷（修改版）、Klee One、Noto Serif CJK SC + 霞鹜文楷、Noto Serif CJK SC + 霞鹜文楷（修改版）。

代码如下（使用 LuaLaTeX 编译）：

``` latex
\documentclass{ltjtarticle}% 用于竖排，横排未发现问题
\usepackage{luatexja-adjust}
\usepackage[match]{luatexja-fontspec}

% 标点调整使用半角式，来自 chinese-jfm 包
\newjfontfamily\onedotming{OneDotMing.ttf}[TateFeatures = {JFM = {zh_CN/{banjiao,vert}}}]
\newjfontfamily\wenkai{LXGWWenKai-Regular.ttf}[TateFeatures = {JFM = {zh_CN/{banjiao,vert}}}]
\newjfontfamily\wenkaimod{LXGWWenKaiMod-Regular.ttf}[TateFeatures = {JFM = {zh_CN/{banjiao,vert}}}]
% TeX 对文件名中含有两个以上点的文件支持不太好，原文件为 I.Ming-7.01.ttf
\newjfontfamily\klee{KleeOne-Regular.ttf}[TateFeatures = {JFM = {ja_JP/{banjiao,vert}}}]
% Ubuntu 自带，故直接使用字体名
\newjfontfamily\notoserifcjk{Noto Serif CJK SC}[TateFeatures = {JFM = {zh_CN/{banjiao,vert}}}]

\begin{document}

\notoserifcjk 你好，世界！

\onedotming 你好，世界！

\wenkai 你好，世界！

\wenkaimod 你好，世界！

\klee 你好，世界！

\notoserifcjk
这是{\wenkai 楷体}文本

这是{\wenkaimod 楷体}文本

\end{document}
```

本人对字体方面了解不是很透彻，但用 FontForge 比较几款字体后发现，只有霞鹜文楷字体信息中“一般 (General)”标签下“有垂直尺寸 (Has Vertical Metrics)”没有被勾选。将其勾选并重新导出字体后，问题消失。注意，当在同一个文档中读取原版字体及修改版字体时，二者的字体名、字族名不应相同。我在修改版字体名和字族名后面都加了 `Mod`。

不知道落霞孤鹜先生制作字体用的是什么软件？希望以上内容能帮助您修复问题。最后感谢您对 FOSS 字体界做出的巨大贡献！

**Comment by lxgw** [comment]
Font Creator。

**Comment by lxgw** [comment]
下个版本会考虑修复这个问题。不过取消竖排度量，也是为了造字方便。

**Comment by lhy7889678** [comment]
好的。不过实践表明，在 FontForge 中开启 Vertical Metrics 后不必进行其他操作，即可正常使用。（修改字体名是为了保证和原版同时读取时不出现冲突，不是必需操作）Font Creator 没有用过，不太了解……

（PS：您的其他字体也存在该问题）

**Comment by lxgw** [comment]
1.100 版本已更新。

**Comment by NightFurySL2001** [comment]
这个恐怕是LaTeX的问题；InDesign无法重现此问题。
