### ISSUE TITLE
请勿仅仅使用版本号后缀来发布不同的字体

### ISSUE THREAD

**Issue by oldherl** [lxgw/LxgwWenKai#35]
我是 archlinuxcn 仓库的维护者，我在该仓库维护了为 Arch Linux 准备的本字体的[软件包](https://github.com/archlinuxcn/repo/tree/master/archlinuxcn/ttf-lxgw-wenkai)。

我看到你使用 v1.007-ui-beta.1 这个 pre-release tag 来发布了另一字体（UI变种），且该tag内不包含原有的字体的文件。它如果正常发布，会使我的自动更新脚本认为它是原字体的新版，而自动用它覆盖掉旧版本。幸好我今天看到了关于UI变种的消息，已经停止了自动更新。

如果你确定要在这个repo内发布新字体，请确保每个tag内都包含两个字体的文件，以免出现自动化脚本误判，将一种字体更新为另一种字体。

**Comment by lxgw** [comment]
了解，会考虑另建一个仓库（repo）。
