### ISSUE TITLE
问号、叹号、分号与冒号位置

### ISSUE THREAD

**Issue by jeffreyxuan** [lxgw/LxgwWenKai#36]
GB/T15834-2011中，5.2.1 竖排文稿标点符号位置和书写形式:

句号、问号、叹号、顿号、分号与冒号均置于相应文字之下偏右。

<img width="188" alt="螢幕快照 2021-10-04 下午2 49 29" src="https://user-images.githubusercontent.com/14179988/135790052-6fd08ef5-816d-44ea-a245-d6327cb4e114.png">

目前 1.10001版本中, 0xfe13~fe16 , 4个直排用的标点符号字符则是置中对齐

**Comment by lxgw** [comment]
直排标点居中是个人习惯。
