### ISSUE TITLE
征求各个字重的命名方式

### ISSUE THREAD

**Issue by lxgw** [lxgw/LxgwWenKai#37]
本字体是按照猫啃网 **Kuiba** 的建议，将原本的 Medium 改成 Bold。

> 如果只是两个字重，建议定义为 Regular 和 Bold (现在是 Regular 和 Medium)。当前方案会存在一个问题：
在 WPS 中，如果使用了粗体，在导出 PDF 时，查看 PDF 文件的字体属性，会发现默认使用（也只使用了 Medium 字重），f直接忽略 了 Regular 字重。（如果用于文稿打印，Regular 字重会细一点，更符合文稿效果，同时也更省墨水/碳粉）。
>（如果是 Regular 和 Bold 字重组合，则 PDF 中会同时嵌入这两个字重）。
>
> 想把 Medium 的字重信息，改成 bold 粗体，方便 Linux 操作系统用户，以及用 LaTeX 排版软件写文稿和论文的用户需求。保留作者版权信息、版本信息、字体内容不作任何修改。不知是否合适？
> 
> *——来自 [猫啃网](https://www.maoken.com/freefonts/9704.html/comment-page-1) **Kuiba** 的评论*

因此，自 0.301 版本开始，将原 Medium 字重改为 Bold 字重。

但经其他用户反馈，将原 Medium 字重作为 Regular 字重的粗体，使用起来并不方便。

> Regular与Bold重名了，如果不是有意为之还是分别命名吧，对于松鼠党来说，三种字体只能安装两个很难受的
> 
> *——来自 [猫啃网](https://www.maoken.com/freefonts/9704.html/comment-page-1) **硬币姬的小迷妹** 的评论*

由此，1.007 和 1.008 版本制作了以现 Bold 字重（原 Medium）为基准字重的「霞鹜文楷 UI」，但却有人认为「会造成混乱和误解」。（[详见此微博评论区](https://weibo.com/6624339726/KwEZxD5SP)）

所以，在此征求各个字重（尤其是 Bold）字重的命名方式。

**Comment by magisk317** [comment]
3个字重如何对应模板里的9个字重？
还是说只能配置345三个字重？
![Image](https://github.com/user-attachments/assets/668f1a8c-3e66-4032-bcb2-ebda9bdd5c8a)
