### ISSUE TITLE
使用 Releases 发布 ttf 文件

### ISSUE THREAD

**Issue by ouuan** [lxgw/LxgwWenKai#4]
建议使用 [Releases](https://docs.github.com/cn/github/administering-a-repository/managing-releases-in-a-repository) 发布 ttf 文件：

1. 用户可以通过 Watch Releases 获取新版本发布通知。
2. 会经常发生改动的二进制文件放在 tree（代码树？就是不是 release 而是仓库中）里不太好，clone 时所有历史版本都会占用空间，时间久了可能导致仓库非常大。

![图片](https://user-images.githubusercontent.com/30581822/107869013-7f1a2f80-6ec4-11eb-9ae6-07a4355a9371.png)

![图片](https://user-images.githubusercontent.com/30581822/107869019-83dee380-6ec4-11eb-8080-b4976eb6abca.png)

**Comment by lxgw** [comment]
那么就不需要在仓库里上传 TTF 文件？

**Comment by ouuan** [comment]
> 那么就不需要在仓库里上传 TTF 文件？

嗯

**Comment by ouuan** [comment]
主要就是看有没有链接 link 到的仓库里面，感觉可以在原位置放个 txt 写上“请到 Releases 下载”之类的
