### ISSUE TITLE
字体的源代码，可以提供吗？

### ISSUE THREAD

**Issue by atzlinux** [lxgw/LxgwWenKai#42]
看到 Klee 字体项目，有提供源代码：

https://github.com/fontworks-fonts/Klee/tree/master/sources

同时还希望提供下由源代码编译成字体的编译脚本和工具：
如：
https://github.com/fontworks-fonts/Klee/blob/master/build.py

如果不提供源代码的话，可能无法通过 Debian 的版权审核。

**Comment by lxgw** [comment]
看样子好像需要 Glyphs 软件，不过我没有  Mac（

**Comment by NightFurySL2001** [comment]
@atzlinux  Klee制作的软件是Mac的Glyphs，这里的源代码是FontCreator的fcp文件（在FCP文件夹内），目前确实只能通过FontCreator导出后才能生成文件而无法使用Python导出。

**Comment by lxgw** [comment]
> @atzlinux  Klee制作的软件是Mac的Glyphs，这里的源代码是FontCreator的fcp文件（在FCP文件夹内），目前确实只能通过FontCreator导出后才能生成文件而无法使用Python导出。
> 

而且 Font Creator 格式文件里包含的也只有部分旧版字形。

**Comment by atzlinux** [comment]
有 Debian 正式成员对没有字体源代码的情况，保留了意见：

https://lists.debian.org/debian-chinese-gb/2021/12/msg00007.html

我也回邮件做了解释，接下来看下其它人的意见了。

**Comment by NightFurySL2001** [comment]
看起来是允许直接在 Github 内上传字体…… 那么 @lxgw 可以试看开新的分支 (branch) 然后上传字体，也可以同时透过 Release 发布。

**Comment by atzlinux** [comment]
> > @atzlinux  Klee制作的软件是Mac的Glyphs，这里的源代码是FontCreator的fcp文件（在FCP文件夹内），目前确实只能通过FontCreator导出后才能生成文件而无法使用Python导出。
> 
> 而且 Font Creator 格式文件里包含的也只有部分旧版字形。

请问是否可以用 FontCreator 來產生 .ufo 的原代碼吗？

有沒有全部汉字的完整字體源碼，可以提供 .ufo 或是 .glyphs 格式的？

如果有 .ufo 或者 .glyphs 的全部源代码，Debian 这边也可以用 fontmake 软件包构建字体文件。

**Comment by medicalwei** [comment]
.ufo 跟 .glyphs 原代碼有個好處是，這些格式都是可以被 git 以行為單位做管理的，若不考慮與原生格式的相容性，我會建議用這個格式作為可以交換的原始碼

**Comment by atzlinux** [comment]
> 看样子好像需要 Glyphs 软件，不过我没有 Mac（

如果有 Mac 下的 Glyphs 软件就好了，可以把字体导出为 .ufo 格式。

https://glyphsapp.com/zh/learn/working-with-ufo

不知道是否可以请其它有这个软件的朋友，帮忙转换为 .ufo 格式，然后上传到 github 里面来？

**Comment by atzlinux** [comment]
> FontCreator

请这个  FontCreator 可以把字体转换导出为 .ufo 格式吗？

**Comment by atzlinux** [comment]
> 看起来是允许直接在 Github 内上传字体后打包给 Debian…… 那么 @lxgw 可以试看开新的分支 (branch) 然后上传字体，也可以同时透过 Release 发布。

字体文件的具体存放方式，Debian 没有限制的。只是不同的存放方式，对制作 Debian 格式的软件包，工作量不一样。

目前该字体最主要的问题，还是卡在字体源代码这块，有好几个 Debian 正式成员跟我提到此事，担心由于没有源代码，而无法通过 Debian 审核。

**Comment by NightFurySL2001** [comment]
FontCreator 不能导出 ufo，FontForge 可以，但是导出流程相对麻烦一点。我觉得可以试看这样直接push进去，毕竟Debian那边除了你提到的一个人以外没看到其他人提问题，思源字体也没有提供ufo。如果无法通过再通知就好了。

**Comment by atzlinux** [comment]
> FontCreator 不能导出 ufo，FontForge 可以，但是导出流程相对麻烦一点。我觉得可以试看这样直接push进去，毕竟Debian那边除了你提到的一个人以外没看到其他人提问题，思源字体也没有提供ufo。如果无法通过再通知就好了。

关于字体源代码的问题，除了在邮件列表里面公开提到的外， 我还跟另外两个中国人 DD 单独沟通过，他们都提到这个源代码的问题。目前看来不提供源代码二进入 Debian，有点困难。

**Comment by atzlinux** [comment]
https://gitee.com/atzlinux/fonts-cjk-zh-lxgw-wenkai/tree/master/fonts  ,麻烦看下这个目录下的文件，铜豌豆项目成员 https://gitee.com/PokerFace128 帮忙在 Mac 机器上用 Glyphs 软件 转换的，不知道如何？

**Comment by medicalwei** [comment]
> https://gitee.com/atzlinux/fonts-cjk-zh-lxgw-wenkai/tree/master/fonts  ,麻烦看下这个目录下的文件，铜豌豆项目成员 https://gitee.com/PokerFace128 帮忙在 Mac 机器上用 Glyphs 软件 转换的，不知道如何？

有一個重點是原始碼的定義是上游要能編輯的格式

如果不符合這個需求的話基本上就跟開分支沒兩樣了⋯⋯

**Comment by medicalwei** [comment]
> 思源字体也没有提供ufo。如果无法通过再通知就好了。

思源字體雖然目前還沒導入編譯流程，但是其需要的 AFDKO 已經在 Debian 裡面可以從源碼編譯了

目前剩下 SIL OFL Reserved Font Name 這點在授權條款比較麻煩，編譯出來的字體跟上游發布的字體不同理論上也不能用一樣名稱發布

**Comment by atzlinux** [comment]
> 
編譯出來的字體跟上游發布的字體不同, 这里是指 字体文件的 MD5 校验和不一样，都算是不同吗？

**Comment by medicalwei** [comment]
> 編譯出來的字體跟上游發布的字體不同, 这里是指 字体文件的 MD5 校验和不一样，都算是不同吗？

其實我不確定要多嚴謹的相同，如果只是一些 metadata 不影響字體形狀與功能的差異的話有些人可能會覺得沒關係

聲明：我不是律師，以上言論不能當作法律建議

**Comment by PokerFace128** [comment]
抱歉，来晚了。一会提交ufo文件

**Comment by PokerFace128** [comment]
> > https://gitee.com/atzlinux/fonts-cjk-zh-lxgw-wenkai/tree/master/fonts  ,麻烦看下这个目录下的文件，铜豌豆项目成员 https://gitee.com/PokerFace128 帮忙在 Mac 机器上用 Glyphs 软件 转换的，不知道如何？
> 
> 有一個重點是原始碼的定義是上游偏好的編輯格式
> 
> 如果不符合這個需求的話基本上就跟開分支沒兩樣了⋯⋯
什麼是上游偏好的編輯格式？

**Comment by zhangkaizhao** [comment]
为了进所谓的 Debian 官方源，这样做是否有点舍本求末？我建议作者不必为此而增加各种麻烦，FontForge 等工具足以维护这个字体作品。对于字体作品来说，有没有所谓的“源码”真的那么重要吗？其实，Debian 的各种规章制度并不都是这个世界的最佳实践，类似的例子，比如最近这个关于浏览器的 [The Sad State Of Web Browser Support Currently Within Debian](https://www.phoronix.com/scan.php?page=news_item&px=Web-Browser-Packages-Debian)，看看他们都在坚持什么，和现实脱轨到底有多严重？

**Comment by medicalwei** [comment]
> 对于字体作品来说，有没有所谓的“源码”真的那么重要吗？

其實不只 Debian，要能上 Google Fonts 字體也是需要有源碼跟 build process 的

https://github.com/google/fonts/blob/main/CONTRIBUTING.md

**Comment by zhangkaizhao** [comment]
> > 对于字体作品来说，有没有所谓的“源码”真的那么重要吗？
> 
> 其實不只 Debian，要能上 Google Fonts 字體也是需要有源碼跟 build process 的
> 
> https://github.com/google/fonts/blob/main/CONTRIBUTING.md

请问 Google Fonts 服务有非用不可的理由吗？Google Fonts 服务是业界标准吗……
Google Fonts 服务跟任何一个字体作品都没什么关系，除了一些希望在它上面托管的，除此之外有什么值得拿来树标杆的呢？

**Comment by SeaHOH** [comment]
其实主要原因是作者无法使用  Glyphs 开发，如果有，他应该不会拒绝提供。那么解决方法来了：捐赠。新开一个专门用途的捐赠通道，用以筹集 Mac 本体和  Glyphs 授权的费用。

**Comment by PokerFace128** [comment]
> 其实主要原因是作者无法使用  Glyphs 开发，如果有，他应该不会拒绝提供。那么解决方法来了：捐赠。新开一个专门用途的捐赠通道，用以筹集 Mac 本体和  Glyphs 授权的费用。

捐赠是个不错的方案，不过在这之前，我倒可以提供协助。直到筹集 Mac 本体和  Glyphs 授权的费用结束

**Comment by lxgw** [comment]
已经有人要将这款字体提交到 Google Fonts 了：google/fonts#4601

**Comment by atzlinux** [comment]
目前的字体源代码没有问题了，在 Debian 下面，也能够编译出字体文件，谢谢！

**Comment by laubonghaudoi** [comment]
> 请问 Google Fonts 服务有非用不可的理由吗？Google Fonts 服务是业界标准吗……
Google Fonts 服务跟任何一个字体作品都没什么关系，除了一些希望在它上面托管的，除此之外有什么值得拿来树标杆的呢？

@zhangkaizhao 這個問題其實提得很好，我嘗試回答一下。Google Fonts 沒有非用不可的理由，Google Fonts 服務也不是業界標準。不過 Google Fonts 有下面幾個比較特別的地方：

1. Google Fonts 是目前最大的免費字體CDN提供商。CDN 提供商的意思是，所有的網頁開發者和安卓 App 開發者都能夠用一行代碼就在自己的網頁上免費使用 GF 上的字體。這對絕大多數開發者都是很關鍵的工具，因為一般開發者不會有資源和時間來自己host字體。很多知名的網頁開發框架例如 [NextJS](https://nextjs.org/docs/pages/building-your-application/optimizing/fonts#google-fonts) 也只默認支援 Google Fonts 作為字體CDN服務。
2. Google Fonts 也是目前眾多 Google 和非 Google 產品的唯一字型上游倉庫，例如全球最多人用的 Google Doc / Google Slides 就只能使用 GF 上的字體。也就是説，如果想要上億的 Google Docs 用户用到一個字體，就只能把它推上GF，沒有別的途經。

所以可以理解為，GF是世界上最大的字體分發渠道。一隻字體如果上了 Google Fonts，就能讓全世界數十億人看到用到。當然這只是一個選擇，並不是所有字體都需要給全世界人看到。
