### ISSUE TITLE
能将 release 的字体文件打个包么，想提交到 mac 的 homebrew 仓库里

### ISSUE THREAD

**Issue by m01i0ng** [lxgw/LxgwWenKai#44]
https://github.com/Homebrew/homebrew-cask-fonts/blob/master/CONTRIBUTING.md#adding-a-font-cask
最好是这种 release 方式，添加起来比较容易些

**Comment by zhangkaizhao** [comment]
@m01i0ng 支持，最近刚好给这个字体的文件重新打包：
https://github.com/oh-my-home/lxgw-wenkai
以便在自己的 Homebrew Tap 中安装和更新：
https://github.com/oh-my-home/homebrew-fonts
如果官方能使打包分发对 Homebrew 更友好那确实是容易得多了。

**Comment by laopangzi** [comment]
+1

**Comment by gongzhang** [comment]
请问目前是不是还没加到 homebrew？没有的话我来加一下？

**Comment by gongzhang** [comment]
哦找到了，https://github.com/oh-my-home/homebrew-fonts/blob/main/Casks/ttf-lxgw-wenkai.rb 👍
