### ISSUE TITLE
山脊的'脊'字不太符合简体中文的样式

### ISSUE THREAD

**Issue by Zuoqiu-Yingyi** [lxgw/LxgwWenKai#45]
v1.111 样式
![image](https://user-images.githubusercontent.com/49649786/147413844-2702ebe8-5068-41e2-bdd4-d5adfc87cdc2.png)

**Comment by lxgw** [comment]
视作风格，暂不改动。

**Comment by lxgw** [comment]
下个版本将做如下调整。

![](https://s2.loli.net/2021/12/28/MZnd5WVFLT2Ek1i.png)

**Comment by lxgw** [comment]
[已更新]https://github.com/lxgw/LxgwWenKai/releases/tag/v1.112
