### ISSUE TITLE
对 powerline 的支持

### ISSUE THREAD

**Issue by shuizhongyueming** [lxgw/LxgwWenKai#46]
现在的字体包里面没有 powerline 相关的字符，如果终端里面的主题有使用这些字符，字体改成 LXGW WenKai 就会有部分字符不能正常显示。

nerd-font 里面有能够往字体里面补充 powerline 相关字符的[工具](https://github.com/ryanoasis/nerd-fonts#font-patcher)，我这边自己也成功实现了生成。但是想着这个要是能在字体的 release 中一同释出，所有人都能受益

这个是我本机运行的效果图

![image](https://user-images.githubusercontent.com/2059860/147803307-0bfebc7d-75ba-49f0-a21e-a29aa94a7747.png)

**Comment by mmqmzk** [comment]
顺便建议等宽字体里面连字符 (ligatures) 也一起做一下吧.
就是把 `==` 显示得像 `≠` 之类的.

**Comment by hotoo** [comment]
中英文分开设置就可以了。

```viml
  set guifont=Sauce\ Code\ Pro\ Nerd\ Font\ Complete:h14
  set guifontwide=LXGWWenKaiMono-Regular:h16
```

**Comment by shuizhongyueming** [comment]
@hotoo 这个应该是配置的 vim 里面的中英文字体吧，但是在 shell 里面的 powerline 就没法受 vim 的配置影响了。比如我现在用的 iTerm2，能够区分 ascii 字体 和 非 ascii 字体的设置。中文和 powerline 里面的一些特殊字符，都可以经由设置 非 ascii 字体来实现。这个时候就需要 LXGW WenKai 这个字体里面有 powerline 需要的一些字符，不然显示的效果就是一些方框

<img width="601" alt="image" src="https://user-images.githubusercontent.com/2059860/150923151-ea00008a-1585-40ef-b0f3-e5d675d31a3b.png">

**Comment by lxgw** [comment]
看了一下 [Inconsolata for Powerline](https://github.com/powerline/fonts/tree/master/Inconsolata)，私用区多出 7 个字符：

![image](https://user-images.githubusercontent.com/51902309/165296869-4472a177-4a57-41f8-a1f6-603085638faf.png)

下图为本字体所含的私用区字符，多为民俗合字。上面七个字符与下面的字符没有冲突。

![image](https://user-images.githubusercontent.com/51902309/165297039-6a33f101-1345-4bd9-a6d9-ba27422bfea7.png)

目前正在考虑是否在 Mono 版本中加入这些字符。

**Comment by lxgw** [comment]
可以在 https://github.com/lxgw/LxgwWenKai/discussions/72 下载字体，测试一下显示效果。

如果方便的话，可以发个截图。
