### ISSUE TITLE
请问能否为这个项目捐款? 

### ISSUE THREAD

**Issue by nutnutwin** [lxgw/LxgwWenKai#47]
这个字体很好用! 
非常感谢! 

我可以使用Paypal , WeChat , 或者Alipay 
谢谢

**Comment by lxgw** [comment]
https://github.com/lxgw/lxgw/blob/main/Donate.md

**Comment by nutnutwin** [comment]
@lxgw 刚才捐款了(WeChat )
如果能用Paypal 就可以定期支付了
