### ISSUE TITLE
中文字体部分在 macOS 下无法正常显示

### ISSUE THREAD

**Issue by jtappler** [lxgw/LxgwWenKai#48]
测试环境: macOS Catalina v10.15.7
测试软件: Pages, Keynote, Notes
问题: 英文字体可以正常显示，简体中文和繁体中文会 fallback 成默认的黑体。

<img width="1017" alt="Screen Shot 2022-01-15 at 2 37 18 PM" src="https://user-images.githubusercontent.com/6665025/149635552-1ab2371b-f705-4b29-bc5f-5a130c7bafb9.png">

**Comment by lxgw** [comment]
本人不用 macOS，所以问题恕无法复现。

如果其他 macOS 用户也是遇到同样问题，我将标明「仅限 Windows 和 Linux 系统使用」。

**Comment by lxgw** [comment]
如果我有经济条件买个 MacBook，我可能会在 Glyphs 上解决这个问题，这样字体源代码的事也就能解决了；但是现在却只能如此而已。所以很抱歉。

**Comment by jtappler** [comment]
抱歉，我发现是我的问题。
我原本安装的是 clone repo 里的 ttf 文件。文件用 Glyphs 打开后只有 1M 左右，不含任何中文字符。
卸载后重新下载 Releases 里面的版本，就可以在 Mac 下正常使用了。

**Comment by lxgw** [comment]
> 抱歉，我发现是我的问题。
> 我原本安装的是 clone repo 里的 ttf 文件。文件用 Glyphs 打开后只有 1M 左右，不含任何中文字符。
> 卸载后重新下载 Releases 里面的版本，就可以在 Mac 下正常使用了。

看到了，这个字体是一个谚文字体，后面标有 Hangul。
