### ISSUE TITLE
更好的版本编号

### ISSUE THREAD

**Issue by ouuan** [lxgw/LxgwWenKai#5]
现在的版本编号看起来是类似于小数的形式，这样人看得懂，但不规范，而且电脑看不懂（是指一般的用来处理版本号的软件/平台都认为 0.2 是早于 0.11 的）。

建议使用 [semver](https://semver.org/lang/zh-CN/) 规范。至少需要保证版本编号（用 `.` 分隔的）的每一块被看作一个“数字”而非“小数点后”，例如，0.2 应该是一个早于 0.11 的版本。

具体来说，我希望能在 [AUR](https://aur.archlinux.org) 打包字体，但现在的版本命名让我感到困难。

**Comment by lxgw** [comment]
但是 Font Creator 只能设置小数格式的版本号

![yy2TDU.png](https://s3.ax1x.com/2021/02/14/yy2TDU.png)

**Comment by ouuan** [comment]
> 但是 Font Creator 只能设置小数格式的版本号
> 
> ![yy2TDU.png](https://camo.githubusercontent.com/4c655df1c6cc468a9aa3e416e9790253c954e14921dcd8cc40dd8f071ae4a389/68747470733a2f2f73332e617831782e636f6d2f323032312f30322f31342f7979325444552e706e67)

虽然我没用过，但我猜想它是只支持分为两部分的版本号？应该还是可以这样搞: 0.1, 0.2, 0.3, ..., 0.10, 0.11, 0.12, 1.0, 1.1

**Comment by ouuan** [comment]
如果一直保持小数点后三位也可以。
