### ISSUE TITLE
请问如何在IE里参照Wenkai? 

### ISSUE THREAD

**Issue by nutnutwin** [lxgw/LxgwWenKai#50]
公司日语环境下IE里可以找到
https://github.com/be5invis/Sarasa-Gothic
显示为｢Sarasa Fixed Slab J｣(但是不显示SC等

请问怎样设置才能显示出来? 
好像IE里不把LXGW WenKai Mono
看作是日语字体(实际可以显示CJK)

谢谢

---
补充一点, 安装Klee One后在IE里也找不到
https://github.com/fontworks-fonts/Klee

---
再补充一点...
TortoiseGit 设置字体里也找不到, 同样Sarasa可以

**Comment by nutnutwin** [comment]
补充一点安装了Klee One(并重启
在IE里也找不到...
https://github.com/fontworks-fonts/Klee

**Comment by lxgw** [comment]
参考这个 issue：https://github.com/lxgw/LxgwWenKai/issues/31

**Comment by nutnutwin** [comment]
@lxgw 
我看一下好像改Panose? 会有其他问题...
晚点测试一下
谢谢

**Comment by NightFurySL2001** [comment]
@nutnutwin CSS设置内尝试设置 "LXGW Wenkai"、"霞鹜文楷"、"LXGW WenKai Mono"、"霞鹜文楷等宽"？Chrome 可以使用上述两个名称。
