### ISSUE TITLE
安装完字体后不在网易云音乐字体列表中显示

### ISSUE THREAD

**Issue by LHYLHY-git** [lxgw/LxgwWenKai#51]
PC，安装完字体，word等软件里可以正常选字体，但是在网易云音乐更改字体界面下拉列表里无此字体，据我所知某些其他字体也会有这种情况，是字体原因还是软件原因呢？谢谢。

word字体列表：
![image](https://user-images.githubusercontent.com/54893905/150966738-6fd2068e-e28a-4a55-b773-820ea52b780e.png)

网易云音乐字体列表
![image](https://user-images.githubusercontent.com/54893905/150966876-9cabf56b-4007-46d2-9ef0-499d9b7a333b.png)

其他字体出现此情况的报告：https://tieba.baidu.com/p/7288493733

**Comment by lxgw** [comment]
找 LXGW WenKai 试试

**Comment by LHYLHY-git** [comment]
没有名为LXGW Wenkai的字体

所有可用字体列表如下

![image](https://user-images.githubusercontent.com/54893905/151642793-4ec0dea3-18a4-4a93-91ad-fdf9c5817d64.png)

**Comment by lxgw** [comment]
试试「为所有用户安装」

**Comment by pxk888** [comment]
> 这个是网易云音乐 Windows 客户端的老 bug 了，连 TTF 格式的[更纱黑体](https://github.com/be5invis/Sarasa-Gothic)都不支持，更别提 OTF 格式的思源黑体和思源宋体了。

我的网易云可以显示思源黑体,但同样显示不了霞鹜文楷,即使是“为所有用户安装”
![image](https://user-images.githubusercontent.com/25244319/166151301-95012b58-1590-4557-84d5-f9be4c7234c7.png)

**Comment by P03T-life** [comment]
> 这个是网易云音乐 Windows 客户端的老 bug 了，连 TTF 格式的[更纱黑体](https://github.com/be5invis/Sarasa-Gothic)都不支持，更别提 OTF 格式的思源黑体和思源宋体了。
今天才发现网易云支持 CJK 字体了

**Comment by lanzhiquan** [comment]
<img width="429" alt="1" src="https://user-images.githubusercontent.com/11311878/166635075-10748960-468a-4fe2-a0fa-c16cb0119341.png">
