### ISSUE TITLE
“禇” 字缺失

### ISSUE THREAD

**Issue by ethanlinys** [lxgw/LxgwWenKai#55]
看三体发现 “禇岩”的“禇”字缺失，是否考虑加上。

**Comment by lxgw** [comment]
完整版是有这个字的，不过是用 zi2zi 生成的，轮廓比较粗糙就是了；芫荽有这个字，下个版本会在 [Lite 版](https://github.com/lxgw/LxgwWenKai-Lite)补上。

**另外，添字请在 [Issue #33](https://github.com/lxgw/LxgwWenKai/issues/33) 反馈，字形调整请在 [Issue #14](https://github.com/lxgw/LxgwWenKai/issues/14) 反馈，不要另开议题。**
