### ISSUE TITLE
希望也能提供传承字形版

### ISSUE THREAD

**Issue by function98** [lxgw/LxgwWenKai#6]
希望能给像我这样的传承字形爱好者更多的选择

**Comment by lxgw** [comment]
由于字体的风格，目前没有传承字形版的计划。

**Comment by UltimateAmitieKaiNiC** [comment]
既然不支持傳承字形，那麼就出日本字形也可以呀！

**Comment by function98** [comment]
> 既然不支持傳承字形，那麼就出日本字形也可以呀！

那你还不如直接用原版，原版就是日文字形……

**Comment by lxgw** [comment]
[目前已經有了，不過使用的是康熙舊型。原版字體提供的嚴格傳承字形很少。](https://github.com/lxgw/LxgwWenkaiTC)

**Comment by lxgw** [comment]
[目前已經有了，不過使用的是康熙舊型。原版字體提供的嚴格傳承字形很少。](https://github.com/lxgw/LxgwWenkaiTC)
