### ISSUE TITLE
能否制作斜体和powerline版本

### ISSUE THREAD

**Issue by chenzaichun** [lxgw/LxgwWenKai#64]
一直很喜欢Klee字体，看到制作了mono字体，准备拿来编程使用，但是缺少了斜体和powerline支持。对字体制作不熟悉，不知道是否可行。感谢。

**Comment by lxgw** [comment]
看了一下 [Inconsolata for Powerline](https://github.com/powerline/fonts/tree/master/Inconsolata)，私用区多出 7 个字符。目前正在考虑是否在 Mono 版本中加入这些字符。

![image](https://user-images.githubusercontent.com/51902309/165296869-4472a177-4a57-41f8-a1f6-603085638faf.png)

**Comment by chenzaichun** [comment]
好的，感谢。

**Comment by lxgw** [comment]
> 好的，感谢。

可以在 #71 下载字体，测试一下显示效果。

**Comment by chenzaichun** [comment]
![image](https://user-images.githubusercontent.com/127616/165700513-15f3ae44-04b3-41b9-a93d-58b425448a49.png)
