### ISSUE TITLE
“龜”的字形显示错误

### ISSUE THREAD

**Issue by vongi** [lxgw/LxgwWenKai#73]
应该是错误吧，我用小米兰亭Pro，和lxgw显示的不一样，而且后者显示的字形，我用五笔好像打不出来，所以麻烦核对一下

**Comment by Hulenkius** [comment]
![IMG_20220429_001254](https://user-images.githubusercontent.com/32562298/165797470-887d6d72-d267-4658-beeb-f3a7b059181b.jpg)

**Comment by lxgw** [comment]
目前只改简体，繁体由于涉及字形更多暂时不改。「⻱」「⿔」为地区字形差异。
