### ISSUE TITLE
v1.234.56 的压缩包中顶层文件夹为 v1.234.5.6，多了个点

### ISSUE THREAD

**Issue by ouuan** [lxgw/LxgwWenKai#74]
v1.234.56 的压缩包中顶层文件夹为 v1.234.5.6，这破坏了我自动打包的逻辑

我是觉得 123456 这种版本号真的没啥意思..如果真要搞也请不要搞出压缩包里面文件夹名称不是版本号这种事

**Comment by lxgw** [comment]
收到，发现这个问题了，马上修改

**Comment by lxgw** [comment]
收到，才发现这个问题了，已经修改。

接受您的批评，以后若有更新会慎重考虑。

对给您带来的不便深表歉意。

**Comment by lxgw** [comment]
至于版本号，是因为字体文件版本号日期为 5 月 6 日，正好也算 1.234 的一个小版本更新。下次更新不会出现这样的问题，会更加慎重。
