### ISSUE TITLE
Spotify 黑框问题

### ISSUE THREAD

**Issue by Jisu-Woniu** [lxgw/LxgwWenKai#78]
Android 版 Spotify 中大部分图标显示为黑框，疑似霞鹜文楷缺少图标部分的字体。

![Spotify截图1](https://user-images.githubusercontent.com/31986081/170634387-b6aeaee3-5f3c-4297-8adf-0e67eaf0d2e0.jpg)

![Spotify截图2](https://user-images.githubusercontent.com/31986081/170634515-23253983-5f17-4da5-acc9-e565e6aa86ad.jpg)

改用系统默认字体后：

![正常截图1](https://user-images.githubusercontent.com/31986081/170634875-dd9e713e-ebf7-4ccd-8380-d87df516cbd1.jpg)

![正常截图2](https://user-images.githubusercontent.com/31986081/170634947-b9ae5553-e458-45dd-8882-207b14d3fbc4.jpg)

**Comment by Jisu-Woniu** [comment]
具体字符编码位不太确定，抱歉

**Comment by lxgw** [comment]
这个问题与手机替换字体的方式有关，替换其他字体可能也会出现这个问题。看界面好像是 Flyme？

**Comment by lxgw** [comment]
**请提供机型、系统版本和更换字体的方式。**或者看看其他字体有没有一样的问题。

个人认为这种问题与本字体无关，属于手机系统字体更换机制的问题，换成其他字体应该也会出现类似的问题，因为其他的字体也未必能有 Spotify 的播放控制符号。Spotify 看样子是内置字体，您所给的图中应该是把 Spotify 内置的西文字体覆盖了，Magisk 应该不是这种效果。当然，我应该没有您所持手机的机型，也没用过 Spotify，所以该问题应该恕无法复现。

最后，有关手机字体替换的问题，请不要在本项目的 issue 下反馈。

**Comment by Jisu-Woniu** [comment]
小米红米K30 Pro，主题壁纸应用下载安装

**Comment by Jisu-Woniu** [comment]
有一部分字体也有类似缺字情况，但形式有所不同（如黑框形状不同或显示NO GLYPH小字），应该与字体本身有关
