### ISSUE TITLE
基于霞鹜文楷衍生的字体命名为秋水書体是否合适的疑问

### ISSUE THREAD

**Issue by NoHeartPen** [lxgw/LxgwWenKai#84]
作为一个日语专业的学生，花了很多时间来找基于日文字形又收录有较多简体字的楷体字体，偶然得知霞鹜文楷时，心里非常高兴（已经安利了小半个日语系了哈哈），但我稍有一点不太满意的就是：出于学习日语的需要，我更希望只是补全简体字，不修改那些中日字形有区别的地方。此前不太好意思提出来，觉得这个需求太过小众了，劳烦您再做一个分支不太好。

前几天发现了您用来制作 LXGW Bright 的字体合并工具，试着做了一个以 Ysabeau 和 Klee 的字体为准，用霞鹜文楷来补全的字体：

![image](https://user-images.githubusercontent.com/79316356/188140777-43121321-8256-4921-ac7a-4b4ee93ef101.png)

由于想把这个字体分享给更多学习日语的同学，想把这个字体开源出来，但不知道我这样制作的字体算是修改了源代码吗？我注意到在`限制`里有这样一条要求：

> 而在没有对字体源代码进行修改的情况下，重新编译出来的字体，可以继续使用本字体的保留名称「霞鹜」

这是不是意味着我需要给字体起一个名字呢？

出于对于霞鹜文楷的敬意，我想以`落霞与孤鹜齐飞`的下半句`秋水共长天一色`给字体起名`秋水書体`，英文名`QiuShuiShotai`——既能表示这个字体主要使用了霞鹜文楷的字形，也能暗示这是以日文字形优先的教科書体。

不知道这样做是否妥当，所以专门通过 issue 的形式询问一下您的意见。

（不好意思，我在字体方面完全是一个小白，啰啰嗦嗦写了这么长，就为了问这么件琐碎的事情）

**Comment by lxgw** [comment]
完全可以

**Comment by NoHeartPen** [comment]
感谢理解和支持:)
项目地址是https://github.com/NoHeartPen/QiushuiShotai
