### ISSUE TITLE
是不是没有集成 nerd font ，导致网页有些图标不显示。

### ISSUE THREAD

**Issue by taixs** [lxgw/LxgwWenKai#85]
使用的是 edge 浏览器，除了等宽字体都设置为 lxgwwenkai 字体，结果会经常出现网页上缺乏某些操作图标的问题。
是浏览器设置不对？还是因为没有集成图标字体的原因？

**Comment by lxgw** [comment]
截图

**Comment by lyhic-mgp** [comment]
我在使用 LXGW WenKai 字体时也遇到了[Nerd Fonts](https://github.com/ryanoasis/nerd-fonts/blob/master/readme_cn.md)图标不显示的问题，我觉得原因是没有集成图标字体。

例如，这是使用含有 Nerd fonts 的 [Sarasa-Mono-SC-Nerd 字体](https://github.com/laishulu/Sarasa-Mono-SC-Nerd)，在使用 powerlevel10k 主题的 zsh 命令行中呈现的效果。
（为方便换字体，使用 Windows Terminal 作为显示终端）
![image](https://user-images.githubusercontent.com/66068243/196626905-5eb91bbf-8ab1-40cb-85ff-d2d56cf3231d.png)
![image](https://user-images.githubusercontent.com/66068243/196628361-8ba44954-af16-41c5-9793-1cf284e7e50a.png)

---

而这是 LXGW WenKai 字体，在其他条件不变的情况下显示的效果。
![image](https://user-images.githubusercontent.com/66068243/196626759-5e6d100e-9126-4cd6-9526-1b3b6c07046a.png)
![image](https://user-images.githubusercontent.com/66068243/196628451-fea76baf-101c-468a-9580-2f65a054c49d.png)

可以看到，英文、汉字、emoji可以正常显示，但命令行的左侧出现了乱码

**Comment by lxgw** [comment]
文楷等宽只适配了基本的 Powerline 符号，没有集成完整的 Nerd Fonts 图标。

**Comment by AshSwing** [comment]
> 文楷等宽只适配了基本的 Powerline 符号，没有集成完整的 Nerd Fonts 图标。

后续是否有考虑集成完整的NerdFonts图标

**Comment by lxgw** [comment]
> > 文楷等宽只适配了基本的 Powerline 符号，没有集成完整的 Nerd Fonts 图标。
> 
> 后续是否有考虑集成完整的NerdFonts图标

抱歉，并没有考虑。

**Comment by taixs** [comment]
不好意思，才看到。
找来找去，结果发现是 egde 浏览器 dark reader 插件的问题……
关闭就没问题了。
