### ISSUE TITLE
请增加「双倍全角横线」U+2E3A（TWO-EM DASH [⸺]）字符

### ISSUE THREAD

**Issue by fanhan-inside** [lxgw/LxgwWenKai#87]
按照W3C的推荐规范，「波折号」应该使用这个字符，目前常见的实现都没有遵守：

> 破折号表示语气或声音的延续、语意的转换或行文的补充。呈现上为一条在水平和垂直方向均位于字面正中的直线，占两个汉字空间。==推荐使用占两个汉字宽度的U+2E3A TWO-EM DASH [⸺]==，但通常也使用两个连续的U+2014 EM DASH [—]来实现。
>
> ⸺[Requirements for Chinese Text Layout - 中文排版需求 (w3.org)](https://www.w3.org/TR/clreq/#categories_and_usage_of_punctuation_marks)

各种中文输入法也是一样，默认的波折号是两个全角横线字符，中间还可以手动（甚至自动）分割换行，不符合各种排版规范（不可分割的连字）⸺不过有些输入法可以设置，正如这段话中使用的波折号那样。

所以希望项目组可以「举手之劳」，用现成的全角横线拼凑一个双倍长度的横线放进字体。

**Comment by lxgw** [comment]
这个字符加进去的话，如果做对应的竖向排版字形，字形过高会把行距撑大。

**Comment by lxgw** [comment]
[新版本已加入。](https://github.com/lxgw/LxgwWenKai/releases/tag/v1.245)
