### ISSUE TITLE
Smaller Fontweight

### ISSUE THREAD

**Issue by sekkit** [lxgw/LxgwWenKai#9]
I noticed the regular font weight is way heavier than Klee One's.
Could you make a lighter verision of it. Thx.
<img width="256" alt="微信截图_20210220003918" src="https://user-images.githubusercontent.com/25851211/108533586-1d1e5780-7314-11eb-8cfa-66460dac02a3.png">

**Comment by lxgw** [comment]
The Klee font looks light on mobile screens especially on Android mobile screens, thus WenKai font's regular weight is modified from Klee's semibold weight, the bolder one.

**Comment by lxgw** [comment]
If I make the font-weight thinner in some simple ways like Font Creator's "Effect->Thin" function, The contours of some glyphs will become terrible. Additionally, it's time-consuming and tiring to create new characters and modify some existing characters, and if I do the same work on another weight, the workload will double. 

So I feel sorry that I couldn't make a thinner font-weight in a short time.

**Comment by lxgw** [comment]
If someone can help me make the thinner one like Klee's regular weight, I'll be appreciate.

**Comment by sekkit** [comment]
ok, maybe it could be done by making an automated script.
