### ISSUE TITLE
GB 屏幕阅读版、GB 粗体《隐》字显示不出来

### ISSUE THREAD

**Issue by m430** [lxgw/LxgwWenKai#90]
![image](https://user-images.githubusercontent.com/4023173/196861055-8803a92c-a361-4530-b56d-db454ce1c7e9.png)

操作系统：macOS Monterey 12.4
软件：Obsidian 1.0

@lxgw

_Originally posted by @m430 in https://github.com/lxgw/LxgwWenKai/issues/33#issuecomment-1284933502_

**Comment by lxgw** [comment]
试试[这个](https://lxgw.lanzoum.com/iEkfz0e8q7lc)，看看能不能显示。

**Comment by m430** [comment]
这个可以正常显示。 @lxgw

**Comment by lxgw** [comment]
是的，抽个空正式更新一下。

**Comment by m430** [comment]
好的。那我先close了，release新版本后，link一下这个issue。

**Comment by lxgw** [comment]
[屏幕阅读版文件已替换。](https://github.com/lxgw/LxgwWenKai-Screen/releases/tag/v1.245)

（屏幕阅读版跟随完整版更新 Release）

**Comment by m430** [comment]
非常感谢您的积极回复和响应。希望这套字体越来越好。Great job.
