### ISSUE TITLE
替换字体时，没有【粗体】的选项，列表里只有【普通（无后缀的）】和【Light】可选。

### ISSUE THREAD

**Issue by Jimmy20220531** [lxgw/LxgwWenKai#91]
LXGWWenKai-Bold和LXGWWenKaiMono-Bold，都已经安装了，奇怪嘞。
![屏幕截图 2022-10-21 130003](https://user-images.githubusercontent.com/106609389/197115846-1494c2d6-954e-4ea9-8bdf-872d6ba1cadc.jpg)

**Comment by lxgw** [comment]
需要右面的框里选粗体

**Comment by lxgw** [comment]
下个版本会将 Bold 改回 Medium。
