### ISSUE TITLE
希望Mono版本优化半角逗号和分号

### ISSUE THREAD

**Issue by zhimoe** [lxgw/LxgwWenKai#94]
当前Mono版本的半角分号和逗号和中文全角的非常相似，在代码中使用难以区分开，建议增加区分度，可是适当下移，并增加逗号的尾巴长度，并增加一点点字重。

我会使用一点点fontforge，但是修改后导出ttf中文间距全乱了。
下面图片放大了看着区分度较好，但是在小字号14下区分度很低。
![image](https://user-images.githubusercontent.com/24514012/199639000-393bdeb7-d9fe-4acb-91af-da965e3de508.png)

**Comment by zhimoe** [comment]
上面图片看着区分比较明显，实际小字号（14-16）下难以区分

**Comment by lxgw** [comment]
个人喜好问题。下图是 MacType 下渲染的效果。

![image](https://user-images.githubusercontent.com/51902309/207753087-8647686c-47e0-486f-bdad-80d4f5e75e84.png)
