### ISSUE TITLE
声调符号的变形问题

### ISSUE THREAD

**Issue by Mjzsl123-github** [lxgw/LxgwWenKai#97]
测试文本：【˥˧˨˩ ˩˨˧˥】
声调符号是需要变形的。比如以上的测试文本应该显示成
![image](https://user-images.githubusercontent.com/110514823/205039638-60c38f8c-d420-4760-b209-fb01f8cbb22f.png)
这样或者
![image](https://user-images.githubusercontent.com/110514823/205039725-561e2f7e-3da2-484f-b7d5-1481780f1717.png)
这样。
但是连在一起丝毫不变形是不对的，比如：
![image](https://user-images.githubusercontent.com/110514823/205039882-58da48ff-e45b-4ba4-89df-b892ed0db700.png)

**Comment by lxgw** [comment]
这个需要动 OpenType 特性，但由于涉及字体数量较多（涉及 20 多个字体文件），动起来比较麻烦，而且排列组合比较多，就没有动这个特性，后续可能会删掉这些符号。请您谅解。
